//! v0.2.1 Phase 8e: macros-crate asset generation (formerly
//! `uor-foundation-macros/build.rs`).
//!
//! The proc-macro crate needs three ontology-derived artifacts at compile
//! time:
//!
//!   - `defaults.rs` — constants like `RESIDUE_DEFAULT_MODULUS`, sourced
//!     from `type:ConstraintDefaults` individuals.
//!   - `keywords.rs` — `KNOWN_KEYWORDS` list, sourced from
//!     `conformance:Shape` individuals' `surfaceForm` properties.
//!   - `shape_requirements.rs` — `SHAPE_REQUIRED_KEYS` table mapping each
//!     declaration keyword to its ordered list of required body keys.
//!
//! v0.2.1 Phase 7c.3 had these written by `uor-foundation-macros/build.rs`
//! reading from `uor-ontology` as a build-dep. That broke
//! `cargo publish --dry-run` because `uor-ontology` is `publish = false`
//! and crates.io rejects path deps without a version specifier when the
//! dependent crate is itself published.
//!
//! Phase 8e moves the generation here, into the `uor-crate` codegen pass
//! alongside `foundation/src/enforcement.rs`. The macros crate becomes a
//! pure leaf with zero build deps and ships cleanly. CI drift guard
//! (`git diff --exit-code uor-foundation-macros/src/generated/`) catches
//! stale artifacts.

use anyhow::{Context, Result};
use std::path::Path;

use uor_ontology::model::IndividualValue;
use uor_ontology::Ontology;

/// Write the three macros-crate artifacts to `out_dir` (typically
/// `uor-foundation-macros/src/generated/`).
///
/// # Errors
///
/// Returns an error if the target directory cannot be created or any file
/// cannot be written.
pub fn generate_macros_assets(ontology: &Ontology, out_dir: &Path) -> Result<Vec<String>> {
    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    let mut written: Vec<String> = Vec::new();

    let defaults_body = write_defaults_body(ontology);
    std::fs::write(out_dir.join("defaults.rs"), &defaults_body)
        .with_context(|| format!("failed to write {}", out_dir.join("defaults.rs").display()))?;
    written.push(out_dir.join("defaults.rs").display().to_string());

    let keywords_body = write_keywords_body(ontology);
    std::fs::write(out_dir.join("keywords.rs"), &keywords_body)
        .with_context(|| format!("failed to write {}", out_dir.join("keywords.rs").display()))?;
    written.push(out_dir.join("keywords.rs").display().to_string());

    let shape_reqs_body = write_shape_requirements_body(ontology);
    std::fs::write(out_dir.join("shape_requirements.rs"), &shape_reqs_body).with_context(|| {
        format!(
            "failed to write {}",
            out_dir.join("shape_requirements.rs").display()
        )
    })?;
    written.push(out_dir.join("shape_requirements.rs").display().to_string());

    // mod.rs bundles the three artifacts under one module.
    let mod_body = "\
// @generated by uor-crate from uor-ontology — do not edit manually.
//
// v0.2.1 Phase 8e: macros-crate ontology-derived assets. Regenerated by
// `cargo run --bin uor-crate`.
pub mod defaults;
pub mod keywords;
pub mod shape_requirements;
";
    std::fs::write(out_dir.join("mod.rs"), mod_body)
        .with_context(|| format!("failed to write {}", out_dir.join("mod.rs").display()))?;
    written.push(out_dir.join("mod.rs").display().to_string());

    Ok(written)
}

fn write_defaults_body(ontology: &Ontology) -> String {
    let modulus = ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .find(|i| i.id == "https://uor.foundation/type/ResidueDefaultModulus")
        .and_then(|i| {
            i.properties.iter().find_map(|(k, v)| {
                if *k == "https://uor.foundation/type/defaultValue" {
                    if let IndividualValue::Int(n) = v {
                        return Some(*n as u64);
                    }
                }
                None
            })
        })
        .unwrap_or(256);

    format!(
        "// @generated by uor-crate from uor-ontology — do not edit manually.\n\
         // Sourced from ontology individual type:ResidueDefaultModulus.\n\
         pub const RESIDUE_DEFAULT_MODULUS: u64 = {modulus};\n"
    )
}

fn write_keywords_body(ontology: &Ontology) -> String {
    let mut keywords: Vec<String> = ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .filter(|i| i.type_ == "https://uor.foundation/conformance/Shape")
        .filter_map(|i| {
            i.properties.iter().find_map(|(k, v)| {
                if *k == "https://uor.foundation/conformance/surfaceForm" {
                    if let IndividualValue::Str(s) = v {
                        return Some(s.to_string());
                    }
                }
                None
            })
        })
        .map(|form| {
            form.strip_suffix("-decl")
                .unwrap_or(&form)
                .replace('-', "_")
        })
        .collect();
    keywords.sort();
    keywords.dedup();

    let entries = keywords
        .iter()
        .map(|k| format!("    \"{k}\""))
        .collect::<Vec<_>>()
        .join(",\n");
    format!(
        "// @generated by uor-crate from uor-ontology — do not edit manually.\n\
         // Sourced from conformance:Shape individuals' surfaceForm values.\n\
         pub const KNOWN_KEYWORDS: &[&str] = &[\n{entries},\n];\n"
    )
}

fn write_shape_requirements_body(ontology: &Ontology) -> String {
    let mut entries: Vec<(String, Vec<String>)> = Vec::new();
    for shape in ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .filter(|i| i.type_ == "https://uor.foundation/conformance/Shape")
    {
        let form = shape.properties.iter().find_map(|(k, v)| {
            if *k == "https://uor.foundation/conformance/surfaceForm" {
                if let IndividualValue::Str(s) = v {
                    return Some(s.to_string());
                }
            }
            None
        });
        let keyword = match form {
            Some(f) => f.strip_suffix("-decl").unwrap_or(&f).replace('-', "_"),
            None => continue,
        };

        let required: Vec<String> = shape
            .properties
            .iter()
            .filter_map(|(k, v)| {
                if *k != "https://uor.foundation/conformance/requiredProperty" {
                    return None;
                }
                let iri = match v {
                    IndividualValue::IriRef(s) => *s,
                    _ => return None,
                };
                ontology
                    .namespaces
                    .iter()
                    .flat_map(|n| n.individuals.iter())
                    .find(|i| i.id == iri)
                    .and_then(|c| {
                        c.properties.iter().find_map(|(ck, cv)| {
                            if *ck == "https://uor.foundation/conformance/surfaceKeyword" {
                                if let IndividualValue::Str(s) = cv {
                                    return Some(s.to_string());
                                }
                            }
                            None
                        })
                    })
            })
            .collect();

        entries.push((keyword, required));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let table_entries = entries
        .iter()
        .map(|(kw, reqs)| {
            let vlist = reqs
                .iter()
                .map(|r| format!("\"{r}\""))
                .collect::<Vec<_>>()
                .join(", ");
            format!("    (\"{kw}\", &[{vlist}])")
        })
        .collect::<Vec<_>>()
        .join(",\n");
    format!(
        "// @generated by uor-crate from uor-ontology — do not edit manually.\n\
         // Each entry: (declaration keyword, &[required body keys]).\n\
         // Sourced from conformance:Shape.requiredProperty -> PropertyConstraint.surfaceKeyword.\n\
         pub const SHAPE_REQUIRED_KEYS: &[(&str, &[&str])] = &[\n{table_entries},\n];\n"
    )
}
