-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Conformance_ individual constants.

import UOR.Structures

open UOR.Primitives

namespace UOR.Bridge.Conformance_

-- Exactly one root term is required. Range is schema:Term.
def compileUnit_rootTerm_constraint : UOR.Bridge.Conformance_.PropertyConstraint UOR.Prims.Standard := {
  constraintProperty := some (("https://uor.foundation/reduction/rootTerm" : String))
  constraintRange := some (("https://uor.foundation/schema/Term" : String))
  minCount := some ((1 : Nat))
  maxCount := some ((1 : Nat))
}

-- At least one target verification domain is required. maxCount 0 means unbounded.
def compileUnit_targetDomains_constraint : UOR.Bridge.Conformance_.PropertyConstraint UOR.Prims.Standard := {
  constraintProperty := some (("https://uor.foundation/reduction/targetDomains" : String))
  constraintRange := some (("https://uor.foundation/op/VerificationDomain" : String))
  minCount := some ((1 : Nat))
  maxCount := some ((0 : Nat))
}

-- Exactly one thermodynamic budget is required. Shape validates presence and type; the BudgetSolvencyCheck preflight validates the value against the Landauer bound.
def compileUnit_thermodynamicBudget_constraint : UOR.Bridge.Conformance_.PropertyConstraint UOR.Prims.Standard := {
  constraintProperty := some (("https://uor.foundation/reduction/thermodynamicBudget" : String))
  constraintRange := some (("http://www.w3.org/2001/XMLSchema#decimal" : String))
  minCount := some ((1 : Nat))
  maxCount := some ((1 : Nat))
}

-- Exactly one quantum level is required. Range is schema:WittLevel.
def compileUnit_unitWittLevel_constraint : UOR.Bridge.Conformance_.PropertyConstraint UOR.Prims.Standard := {
  constraintProperty := some (("https://uor.foundation/reduction/unitWittLevel" : String))
  constraintRange := some (("https://uor.foundation/schema/WittLevel" : String))
  minCount := some ((1 : Nat))
  maxCount := some ((1 : Nat))
}

-- Shape validating that a CompileUnit carries all required properties before reduction admission. The unitAddress property is NOT required — it is computed by stage_initialization after shape validation passes.
def CompileUnitShape : UOR.Bridge.Conformance_.Shape UOR.Prims.Standard := {
  targetClass := some (("https://uor.foundation/reduction/CompileUnit" : String))
  requiredProperty := #[UOR.Bridge.Conformance_.compileUnit_rootTerm_constraint, UOR.Bridge.Conformance_.compileUnit_unitWittLevel_constraint, UOR.Bridge.Conformance_.compileUnit_thermodynamicBudget_constraint, UOR.Bridge.Conformance_.compileUnit_targetDomains_constraint]
}

end UOR.Bridge.Conformance_
