-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Type_ individual constants.

import UOR.Structures

open UOR.Primitives

namespace UOR.User.Type_

-- The canonical binary disjoint union type whose carrier is L + R.
def EitherType : UOR.User.Type_.SumType UOR.Prims.Standard := {
  contentAddress := none
}

-- Nodes with edge constraints. Constraint nerve = graph topology.
def GraphType : UOR.User.Type_.ConstrainedType UOR.Prims.Standard := {
  baseType := none
  hasConstraint := #[]
  holonomyGroup := none
  monodromyClass := none
  holonomyClassified := none
  contentAddress := none
}

-- The canonical A + Unit idiom for optional values.
def OptionType : UOR.User.Type_.SumType UOR.Prims.Standard := {
  contentAddress := none
}

-- A single value from an ordered domain. siteCount = n (quantization bits).
def ScalarType : UOR.User.Type_.PrimitiveType UOR.Prims.Standard := {
  bitWidth := none
  contentAddress := none
}

-- An ordered list of elements with backbone constraint. The free monoid on the element type.
def SequenceType : UOR.User.Type_.ProductType UOR.Prims.Standard := {
  component := #[]
  contentAddress := none
}

-- Unordered collection. d_delta is permutation-invariant.
def SetType : UOR.User.Type_.ConstrainedType UOR.Prims.Standard := {
  baseType := none
  hasConstraint := #[]
  holonomyGroup := none
  monodromyClass := none
  holonomyClassified := none
  contentAddress := none
}

-- A value from a finite unordered set. siteCount = ceil(log2(|alphabet|)).
def SymbolType : UOR.User.Type_.PrimitiveType UOR.Prims.Standard := {
  bitWidth := none
  contentAddress := none
}

-- Collection of tuples sharing a schema = Sequence(Tuple(S)). Functorial decomposition.
def TableType : UOR.User.Type_.ProductType UOR.Prims.Standard := {
  component := #[]
  contentAddress := none
}

-- Hierarchical structure. beta_1=0 (acyclic), beta_0=1 (connected).
def TreeType : UOR.User.Type_.ConstrainedType UOR.Prims.Standard := {
  baseType := none
  hasConstraint := #[]
  holonomyGroup := none
  monodromyClass := none
  holonomyClassified := none
  contentAddress := none
}

-- A fixed collection of named fields.
def TupleType : UOR.User.Type_.ProductType UOR.Prims.Standard := {
  component := #[]
  contentAddress := none
}

end UOR.User.Type_
