// @generated by uor-crate from uor-ontology — do not edit manually

//! Phase 10 stubs for the `ih` theorem family.
//!
//! Each `verify_*` is a Phase-10 placeholder returning
//! `Err(GenericImpossibilityWitness::for_identity("WITNESS_UNIMPLEMENTED_STUB:{IRI}"))`.
//! Phase 12 replaces each body with the real verification.

use crate::enforcement::GenericImpossibilityWitness;
use crate::witness_scaffolds::{
    MintImpossibilityWitness, MintImpossibilityWitnessInputs, MintInhabitanceImpossibilityWitness,
    MintInhabitanceImpossibilityWitnessInputs,
};
use crate::HostTypes;

/// Phase-10 stub for `https://uor.foundation/op/IH_1`.
///
/// # Errors
///
/// Always returns `WITNESS_UNIMPLEMENTED_STUB:https://uor.foundation/proof/ImpossibilityWitness` until
/// Phase 12 fills the body.
pub fn verify_proof_impossibility_witness<H: HostTypes>(
    inputs: MintImpossibilityWitnessInputs<H>,
) -> Result<MintImpossibilityWitness, GenericImpossibilityWitness> {
    let _ = inputs;
    Err(GenericImpossibilityWitness::for_identity(
        "WITNESS_UNIMPLEMENTED_STUB:https://uor.foundation/proof/ImpossibilityWitness",
    ))
}

/// Phase-10 stub for `https://uor.foundation/op/IH_1`.
///
/// # Errors
///
/// Always returns `WITNESS_UNIMPLEMENTED_STUB:https://uor.foundation/proof/InhabitanceImpossibilityWitness` until
/// Phase 12 fills the body.
pub fn verify_proof_inhabitance_impossibility_witness<H: HostTypes>(
    inputs: MintInhabitanceImpossibilityWitnessInputs<H>,
) -> Result<MintInhabitanceImpossibilityWitness, GenericImpossibilityWitness> {
    let _ = inputs;
    Err(GenericImpossibilityWitness::for_identity(
        "WITNESS_UNIMPLEMENTED_STUB:https://uor.foundation/proof/InhabitanceImpossibilityWitness",
    ))
}
