// @generated by uor-crate from uor-ontology — do not edit manually

//! Phase 10 / 12 — per-family verify primitives for Path-2 witnesses.
//!
//! Each submodule hosts the stubbed (Phase 10) or real (Phase 12)
//! `verify_*` primitives that back the
//! `OntologyVerifiedMint::ontology_mint` impls in
//! `crate::witness_scaffolds`. Stub bodies return
//! `Err(GenericImpossibilityWitness::for_identity("WITNESS_UNIMPLEMENTED_STUB:{IRI}"))`.

pub mod br;
pub mod cc;
pub mod dp;
pub mod ih;
pub mod lo;
pub mod oa;
