-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Content Addressing namespace structures.

import UOR.Primitives
import UOR.Enums

open UOR.Primitives

/-- A content-addressable ring element. Each Element uniquely identifies a piece of content via its hash-derived identifier. -/
structure Element (P : Primitives) where
  /-- The number of Braille glyphs in an address string. -/
  length : P.NonNegativeInteger
  /-- The datum that this address references. Inverse of schema:glyph. -/
  addresses : P.String
  /-- The content hash of this address. Format: (blake3|sha256) colon followed by 64 lowercase hex characters. The algorithm prefix must match u:digestAlgorithm. -/
  digest : P.String
  /-- The hash algorithm used to produce u:digest. Allowed values: 'blake3' (primary), 'sha256' (secondary). -/
  digestAlgorithm : P.String
  /-- The canonical byte serialisation of the addressed datum, per Amendment 43 section 2: header(k) || le_bytes(x, k+1). This is the exact byte string hashed to produce u:digest. -/
  canonicalBytes : P.String
  /-- The Witt level n of this element. The element encodes a datum in R_n = Z/(2^n)Z. -/
  wittLength : P.PositiveInteger
