-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Division Algebras namespace structures.

import UOR.Primitives
import UOR.Enums

open UOR.Primitives

/-- An algebra over R that is a division ring with multiplicative norm. Exactly four exist (Hurwitz theorem): R, C, H, O. -/
structure NormedDivisionAlgebra (P : Primitives) where
  /-- The dimension of this division algebra (1, 2, 4, or 8). -/
  algebraDimension : P.NonNegativeInteger
  /-- Whether multiplication in this algebra is commutative. -/
  isCommutative : P.Boolean
  /-- Whether multiplication in this algebra is associative. -/
  isAssociative : P.Boolean
  /-- The basis elements of this division algebra. -/
  basisElements : P.String
  /-- The multiplication table for this algebra. -/
  algebraMultiplicationTable : MultiplicationTable P

/-- The doubling construction that builds each division algebra from the previous: R → C → H → O. -/
structure CayleyDicksonConstruction (P : Primitives) where
  /-- The source algebra of the Cayley-Dickson doubling. -/
  cayleyDicksonSource : NormedDivisionAlgebra P
  /-- The target algebra of the Cayley-Dickson doubling. -/
  cayleyDicksonTarget : NormedDivisionAlgebra P
  /-- The new basis element adjoined by this doubling step. -/
  adjoinedElement : P.String
  /-- The conjugation and multiplication rule for the adjoined element. -/
  conjugationRule : P.String

/-- The explicit product rules for a division algebra’s basis elements. -/
structure MultiplicationTable (P : Primitives)

/-- The commutator [a,b] = ab − ba. Zero for R and C; non-zero for H and O. -/
structure AlgebraCommutator (P : Primitives)

/-- The associator [a,b,c] = (ab)c − a(bc). Zero for R, C, H; non-zero for O. -/
structure AlgebraAssociator (P : Primitives)


/-- The real numbers R: dimension 1, commutative, associative. -/
namespace RealAlgebra
def ALGEBRA_DIMENSION : Int := 1
def BASIS_ELEMENTS : String := "{1}"
def IS_ASSOCIATIVE : Bool := true
def IS_COMMUTATIVE : Bool := true
end RealAlgebra

/-- The complex numbers C: dimension 2, commutative, associative. -/
namespace ComplexAlgebra
def ALGEBRA_DIMENSION : Int := 2
def BASIS_ELEMENTS : String := "{1, i}"
def IS_ASSOCIATIVE : Bool := true
def IS_COMMUTATIVE : Bool := true
end ComplexAlgebra

/-- The quaternions H: dimension 4, non-commutative, associative. -/
namespace QuaternionAlgebra
def ALGEBRA_DIMENSION : Int := 4
def BASIS_ELEMENTS : String := "{1, i, j, k}"
def IS_ASSOCIATIVE : Bool := true
def IS_COMMUTATIVE : Bool := false
end QuaternionAlgebra

/-- The octonions O: dimension 8, non-commutative, non-associative. -/
namespace OctonionAlgebra
def ALGEBRA_DIMENSION : Int := 8
def BASIS_ELEMENTS : String := "{1, i, j, k, l, il, jl, kl}"
def IS_ASSOCIATIVE : Bool := false
def IS_COMMUTATIVE : Bool := false
end OctonionAlgebra

/-- Cayley-Dickson doubling R → C: adjoin i with i² = −1. -/
namespace cayleyDickson_R_to_C
def ADJOINED_ELEMENT : String := "i"
def CAYLEY_DICKSON_SOURCE : String := "https://uor.foundation/division/RealAlgebra"
def CAYLEY_DICKSON_TARGET : String := "https://uor.foundation/division/ComplexAlgebra"
def CONJUGATION_RULE : String := "i² = −1"
end cayleyDickson_R_to_C

/-- Cayley-Dickson doubling C → H: adjoin j with j² = −1, ij = k, ji = −k. -/
namespace cayleyDickson_C_to_H
def ADJOINED_ELEMENT : String := "j"
def CAYLEY_DICKSON_SOURCE : String := "https://uor.foundation/division/ComplexAlgebra"
def CAYLEY_DICKSON_TARGET : String := "https://uor.foundation/division/QuaternionAlgebra"
def CONJUGATION_RULE : String := "ij = k, ji = −k"
end cayleyDickson_C_to_H

/-- Cayley-Dickson doubling H → O: adjoin l, non-associative Fano plane products. -/
namespace cayleyDickson_H_to_O
def ADJOINED_ELEMENT : String := "l"
def CAYLEY_DICKSON_SOURCE : String := "https://uor.foundation/division/QuaternionAlgebra"
def CAYLEY_DICKSON_TARGET : String := "https://uor.foundation/division/OctonionAlgebra"
def CONJUGATION_RULE : String := "non-associative Fano plane products"
end cayleyDickson_H_to_O
