-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Failure Algebra namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Bridge.Proof
import UOR.Kernel.Effect
import UOR.Kernel.Reduction
import UOR.Kernel.Schema

open UOR.Primitives

/-- The outcome of a computation that may fail: either a Success carrying a datum, or a Failure carrying a typed reason. The coproduct of the success and failure cases. -/
structure ComputationResult (P : Primitives)

/-- A computation that reached convergence and produced a valid datum. Carries the output datum and the computation certificate. -/
structure Success (P : Primitives) extends ComputationResult P where
  /-- The output datum of a successful computation. -/
  resultDatum : UOR.Kernel.Schema.Datum P
  /-- The certificate attesting the computation’s correctness. -/
  resultCertificate : UOR.Bridge.Proof.ComputationCertificate P

/-- A computation that could not reach convergence. Carries a typed FailureReason and the reduction state at the point of failure. -/
structure Failure (P : Primitives) extends ComputationResult P where
  /-- The typed reason for failure. -/
  failureReason : FailureReason P
  /-- The reduction state at the point of failure. -/
  failureState : UOR.Kernel.Reduction.ReductionState P
  /-- The reduction step where failure occurred. -/
  failureStage : UOR.Kernel.Reduction.ReductionStep P
  /-- Available recovery strategies for this failure. -/
  recoveryStrategy : Array (Recovery P)
  /-- The reduction step index at which failure occurred. -/
  failureDepth : P.NonNegativeInteger

/-- A typed classification of why a computation failed. -/
structure FailureReason (P : Primitives)

/-- A reduction step guard evaluated to false and no alternative transition exists. -/
structure GuardFailure (P : Primitives) extends FailureReason P

/-- Two constraints in the type’s constraint set are jointly unsatisfiable. -/
structure ConstraintContradiction (P : Primitives) extends FailureReason P

/-- The linear budget was exhausted before resolution completed. -/
structure SiteExhaustion (P : Primitives) extends FailureReason P

/-- A WittLift encountered a non-trivial obstruction that could not be resolved. -/
structure LiftObstructionFailure (P : Primitives) extends FailureReason P

/-- A computation that produces a ComputationResult rather than a guaranteed datum. The general case of all computations. -/
structure PartialComputation (P : Primitives) where
  /-- True iff the computation is a TotalComputation (no possible failure path). -/
  isTotal : P.Boolean

/-- A computation where the FailureReason type is empty — failure is structurally impossible. -/
structure TotalComputation (P : Primitives) extends PartialComputation P

/-- A strategy for converting a Failure into a Success by modifying the computation path. -/
structure Recovery (P : Primitives) where
  /-- The effect applied to recover from failure. -/
  recoveryEffect : UOR.Kernel.Effect.Effect P
  /-- The reduction step to retry after recovery. -/
  recoveryTarget : UOR.Kernel.Reduction.ReductionStep P

/-- The rule for how failures compose under monoidal and parallel products. -/
structure FailurePropagation (P : Primitives) where
  /-- Which failure reasons propagate through this composition. -/
  propagationRule : Array (FailureReason P)
