-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Parallel Composition namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Bridge.Cert
import UOR.Bridge.Partition
import UOR.Bridge.Trace
import UOR.Kernel.Effect
import UOR.Kernel.Monoidal

open UOR.Primitives

/-- A ∥ B: two computations with provably disjoint site targets. Execution order does not affect the result. -/
structure ParallelProduct (P : Primitives) where
  /-- The left parallel component (itself a sequential computation). -/
  leftComputation : UOR.Kernel.Monoidal.MonoidalProduct P
  /-- The right parallel component. -/
  rightComputation : UOR.Kernel.Monoidal.MonoidalProduct P
  /-- The certificate proving site disjointness. -/
  disjointnessCert : DisjointnessCertificate P
  /-- True iff site targets have zero overlap (no SynchronizationPoints required). -/
  isFullyDisjoint : P.Boolean
  /-- Declares whether this parallel product commutes with disjoint effects per FX_4. -/
  disjointnessCommutation : P.Boolean

/-- A kernel-produced certificate attesting that the site targets of two computations are disjoint. -/
structure DisjointnessCertificate (P : Primitives) extends UOR.Bridge.Cert.Certificate P where
  /-- The site target of the left computation. -/
  certLeftTarget : UOR.Kernel.Effect.EffectTarget P
  /-- The site target of the right computation. -/
  certRightTarget : UOR.Kernel.Effect.EffectTarget P

/-- A point where two parallel computations must agree on shared state before proceeding. Only applicable when parallelism is partial. -/
structure SynchronizationPoint (P : Primitives) where
  /-- The shared sites requiring synchronization. -/
  syncSites : Array (UOR.Bridge.Partition.SiteIndex P)

/-- A computation trace recording interleaved steps from two parallel computations. Valid iff every interleaving produces the same final context. -/
structure ParallelTrace (P : Primitives) extends UOR.Bridge.Trace.ComputationTrace P

/-- A partition of the total site budget into disjoint subsets, one per parallel component. The sum of subset cardinalities equals the total site budget. -/
structure SitePartitioning (P : Primitives) where
  /-- The disjoint subsets composing the full site budget. -/
  partitionComponents : Array (UOR.Kernel.Effect.EffectTarget P)
  /-- Number of parallel components. -/
  componentCount : P.PositiveInteger
