-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR IO Boundary namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Kernel.Effect
import UOR.User.Morphism
import UOR.User.State
import UOR.User.Type_

open UOR.Primitives

/-- A typed interface point between the kernel and the external world. Every data flow into or out of the ring crosses exactly one IOBoundary. -/
structure IOBoundary (P : Primitives)

/-- A typed source of external data entering the ring. Carries an expected TypeDefinition describing the shape of incoming data. -/
structure Source (P : Primitives) extends IOBoundary P where
  /-- The expected type of data arriving from this source. -/
  sourceType : UOR.User.Type_.TypeDefinition P
  /-- The grounding map that transforms incoming surface data to ring datums. -/
  sourceGrounding : UOR.User.Morphism.GroundingMap P

/-- A typed destination for data leaving the ring. Carries an expected TypeDefinition describing the shape of outgoing data. -/
structure Sink (P : Primitives) extends IOBoundary P where
  /-- The expected type of data departing through this sink. -/
  sinkType : UOR.User.Type_.TypeDefinition P
  /-- The projection map that transforms ring datums to outgoing surface data. -/
  sinkProjection : UOR.User.Morphism.ProjectionMap P

/-- An effect that crosses the kernel/external boundary. Specializes effect:ExternalEffect with explicit source or sink binding. -/
structure BoundaryEffect (P : Primitives) extends UOR.Kernel.Effect.ExternalEffect P where
  /-- The boundary this effect crosses. -/
  effectBoundary : IOBoundary P
  /-- True iff applying the boundary effect twice produces the same result as applying it once. -/
  isIdempotent : P.Boolean

/-- A BoundaryEffect that reads from a Source and produces a datum in the ring. -/
structure IngestEffect (P : Primitives) extends BoundaryEffect P where
  /-- The source being read. -/
  ingestSource : Source P

/-- A BoundaryEffect that writes a ring datum to a Sink. -/
structure EmitEffect (P : Primitives) extends BoundaryEffect P where
  /-- The sink being written to. -/
  emitSink : Sink P

/-- A specification of the data shape, ordering, and framing constraints for data crossing a boundary. -/
structure BoundaryProtocol (P : Primitives) where
  /-- The type specification for boundary data. -/
  protocolType : UOR.User.Type_.TypeDefinition P
  /-- Sequencing constraints on boundary data. -/
  protocolOrdering : UOR.User.Type_.CompositeConstraint P

/-- A Session that includes BoundaryEffects. Extends the session model to track which boundaries were crossed. -/
structure BoundarySession (P : Primitives) extends UOR.User.State.Session P where
  /-- The boundaries crossed during this session. -/
  sessionBoundaries : Array (IOBoundary P)
  /-- Total number of boundary crossings in this session. -/
  crossingCount : P.NonNegativeInteger
