-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Homology namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Bridge.Partition
import UOR.User.Type_

open UOR.Primitives

/-- A k-simplex: a finite set of k+1 vertices drawn from constraint objects. -/
structure Simplex (P : Primitives) where
  /-- The dimension k of a simplex (number of vertices minus one). -/
  dimension : P.Integer
  /-- A vertex of this simplex, drawn from the set of constraint objects. -/
  vertex : Array (UOR.User.Type_.Constraint P)
  /-- The number of vertices in this simplex (dimension + 1). -/
  vertexCount : P.PositiveInteger
  /-- Indicates that this simplex is a face of another simplex. -/
  isFaceOf : Array (Simplex P)
  /-- A site coordinate in the partition whose intersection pins this simplex. -/
  pinIntersection : Array (UOR.Bridge.Partition.SiteIndex P)

/-- A simplicial complex: a set of simplices closed under taking faces. -/
structure SimplicialComplex (P : Primitives) where
  /-- A simplex belonging to this simplicial complex. -/
  hasSimplex : Array (Simplex P)
  /-- The maximum dimension of any simplex in this simplicial complex. -/
  maxDimension : P.Integer
  /-- The Euler characteristic of this simplicial complex: the alternating sum of simplex counts by dimension. -/
  eulerCharacteristic : P.Integer
  /-- The total number of vertices (0-simplices) in this simplicial complex. -/
  simplicialVertexCount : P.NonNegativeInteger

/-- A face map d_i: removes vertex i from a simplex, producing a face. -/
structure FaceMap (P : Primitives) where
  /-- The index i of the vertex removed by this face map d_i. -/
  removesVertex : P.NonNegativeInteger
  /-- The source simplex of this face map. -/
  sourceSimplex : Simplex P
  /-- The target face (result simplex) of this face map. -/
  targetFace : Simplex P

/-- A free abelian group generated by k-simplices (the k-th chain group C_k). -/
structure ChainGroup (P : Primitives) where
  /-- The degree k of this chain group (the dimension of its generating simplices). -/
  degree : P.Integer
  /-- A simplex that generates this chain group. -/
  generatedBy : Array (Simplex P)

/-- The boundary operator ∂_k: C_k → C_{k-1}. Satisfies ∂² = 0. -/
structure BoundaryOperator (P : Primitives) where
  /-- The source chain group C_k of this boundary operator. -/
  sourceGroup : ChainGroup P
  /-- The target chain group C_{k-1} of this boundary operator. -/
  targetGroup : ChainGroup P
  /-- Whether this boundary operator satisfies the fundamental property ∂² = 0. -/
  satisfiesBoundarySquaredZero : P.Boolean

/-- A chain complex: a sequence of chain groups connected by boundary operators. -/
structure ChainComplex (P : Primitives) where
  /-- A chain group belonging to this chain complex. -/
  hasChainGroup : Array (ChainGroup P)
  /-- A boundary operator belonging to this chain complex. -/
  hasBoundary : Array (BoundaryOperator P)

/-- The k-th homology group H_k = ker(∂_k) / im(∂_{k+1}). Measures k-dimensional holes. -/
structure HomologyGroup (P : Primitives) where
  /-- The degree k of this homology group H_k. -/
  homologyDegree : P.Integer
  /-- The Betti number β_k = rank(H_k): the rank of this homology group. -/
  bettiNumber : P.NonNegativeInteger

/-- The nerve functor N: maps a set of constraints to a simplicial complex. -/
structure NerveFunctor (P : Primitives)

/-- The chain functor C: maps a simplicial complex to a chain complex. -/
structure ChainFunctor (P : Primitives)

/-- A simplicial set satisfying the Kan extension condition. The constraint nerve, when promoted from a SimplicialComplex to a KanComplex, carries a full homotopy type — not just its homology groups. -/
structure KanComplex (P : Primitives) extends SimplicialComplex P where
  /-- A horn filler witnessing the Kan condition for this complex. -/
  kanWitness : Array (HornFiller P)

/-- A witness that a given horn (an incomplete simplex boundary) can be filled, certifying the Kan condition at a specific dimension and position. -/
structure HornFiller (P : Primitives) where
  /-- The dimension of the horn that this filler completes. -/
  hornDimension : P.NonNegativeInteger
  /-- The position (missing face index) of the horn that this filler completes. -/
  hornPosition : P.NonNegativeInteger

/-- The k-th Postnikov truncation τ≤k of the constraint nerve: a KanComplex whose homotopy groups πj vanish for j > k. -/
structure PostnikovTruncation (P : Primitives) where
  /-- The truncation level k of this Postnikov truncation τ≤k. -/
  truncationLevel : P.NonNegativeInteger
  /-- The KanComplex from which this Postnikov truncation is derived. -/
  truncationSource : KanComplex P
  /-- The k-invariant classifying the extension at this truncation level. -/
  kInvariant : KInvariant P

/-- The k-invariant κk that classifies the extension from the (k−1)-truncation to the k-truncation of the Postnikov tower. Trivial κk means the truncation splits as a product. -/
structure KInvariant (P : Primitives) where
  /-- True iff this k-invariant is trivial, meaning the Postnikov truncation splits as a product. -/
  kInvariantTrivial : P.Boolean

/-- The deformation complex of a CompleteType T: a chain complex whose H⁰ = automorphisms, H¹ = first-order deformations, H² = obstructions to extending deformations. -/
structure DeformationComplex (P : Primitives) extends ChainComplex P where
  /-- The CompleteType whose deformation complex this is. -/
  deformationBase : UOR.User.Type_.CompleteType P
  /-- The dimension of the tangent space H¹(Def(T)): the number of first-order deformations. -/
  tangentDimension : P.NonNegativeInteger
  /-- The dimension of the obstruction space H²(Def(T)): the number of independent obstructions to extending deformations. -/
  obstructionDimension : P.NonNegativeInteger


/-- ∂² = 0: the boundary of a boundary is zero. -/
namespace boundarySquaredZero
def FOR_ALL : String := "https://uor.foundation/schema/term_boundarySquaredZero_forAll"
def LHS : String := "https://uor.foundation/schema/term_boundarySquaredZero_lhs"
def RHS : String := "https://uor.foundation/schema/term_boundarySquaredZero_rhs"
def VERIFICATION_DOMAIN : String := "https://uor.foundation/op/Topological"
end boundarySquaredZero

/-- The nerve functor N: constraints → simplicial complex. -/
namespace nerveFunctorN end nerveFunctorN

/-- The chain functor C: simplicial complex → chain complex. -/
namespace chainFunctorC end chainFunctorC

/-- ψ_4: HomologyGroups → BettiNumbers (extraction functor). -/
namespace psi_4
def FOR_ALL : String := "https://uor.foundation/schema/term_psi_4_forAll"
def LHS : String := "https://uor.foundation/schema/term_psi_4_lhs"
def RHS : String := "https://uor.foundation/schema/term_psi_4_rhs"
def VERIFICATION_DOMAIN : String := "https://uor.foundation/op/Topological"
end psi_4

/-- Index bridge: connects Euler characteristic to alternating Betti sum. -/
namespace indexBridge
def FOR_ALL : String := "https://uor.foundation/schema/term_indexBridge_forAll"
def LHS : String := "https://uor.foundation/schema/term_indexBridge_lhs"
def RHS : String := "https://uor.foundation/schema/term_indexBridge_rhs"
def VERIFICATION_DOMAIN : String := "https://uor.foundation/op/Topological"
end indexBridge
