-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Partitions namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Kernel.Schema
import UOR.User.Type_

open UOR.Primitives

/-- A four-component partition of R_n produced by resolving a type declaration. The four components — Irreducible, Reducible, Units, Exterior — are mutually disjoint and exhaustive over the carrier. -/
structure Partition (P : Primitives) where
  /-- The irreducible component of this partition. -/
  irreducibles : IrreducibleSet P
  /-- The reducible component of this partition. -/
  reducibles : ReducibleSet P
  /-- The units component of this partition. -/
  units : UnitGroup P
  /-- The exterior component of this partition. -/
  exterior : Complement P
  /-- The irreducible density of this partition: |Irr| / |A|, where A is the active carrier. -/
  density : P.Decimal
  /-- The type declaration that was resolved to produce this partition. -/
  sourceType : UOR.User.Type_.TypeDefinition P
  /-- The Witt level n at which this partition was computed. The ring has 2^n elements at this level. -/
  wittLength : P.PositiveInteger
  /-- The site budget associated with this partition. -/
  siteBudget : FreeRank P
  /-- Whether the four components of this partition are exhaustive over R_n: |Irr| + |Red| + |Unit| + |Ext| = 2^n (FPM_8). Set by the kernel after verification. -/
  isExhaustive : P.Boolean

/-- A single component of a partition: a set of datum values belonging to one of the four categories. -/
structure Component (P : Primitives) where
  /-- A datum value belonging to this partition component. -/
  member : Array (UOR.Kernel.Schema.Datum P)
  /-- The number of elements in this partition component. The cardinalities of the four components must sum to 2^n. -/
  cardinality : P.NonNegativeInteger

/-- The set of irreducible elements under the active type: elements whose only factorizations involve units or themselves. Analogous to prime elements in a ring. -/
structure IrreducibleSet (P : Primitives) extends Component P

/-- The set of reducible non-unit elements: elements that can be expressed as a product of two or more non-unit elements. -/
structure ReducibleSet (P : Primitives) extends Component P

/-- The set of invertible elements (units) in the carrier: elements with a multiplicative inverse. In Z/(2^n)Z, the units are the odd integers. -/
structure UnitGroup (P : Primitives) extends Component P

/-- Elements of R_n that fall outside the active carrier — i.e., outside the type's domain. These are ring elements that do not participate in the current type resolution. -/
structure Complement (P : Primitives) extends Component P where
  /-- The formal membership criterion for this Complement: x ∈ Ext(T) iff x ∉ carrier(T). The Complement is context-dependent on the active type T (FPM_9). -/
  exteriorCriteria : UOR.Kernel.Schema.TermExpression P

/-- A single site coordinate in the iterated Z/2Z fibration. Each site represents one binary degree of freedom in the ring's structure. The total number of sites equals the quantum level n. -/
structure SiteIndex (P : Primitives) where
  /-- The zero-based position of this site coordinate within the iterated fibration. Position 0 is the least significant bit; position n-1 is the most significant. -/
  sitePosition : P.NonNegativeInteger
  /-- The current state of this site coordinate: 'pinned' if determined by a constraint, 'free' if still available for refinement. -/
  siteState : P.NonNegativeInteger
  /-- An ancilla site coordinate paired with this site for reversible computation (RC_1–RC_4 ancilla model). -/
  ancillaSite : Option (SiteIndex P)

/-- The site budget for a partition: an accounting of how many sites are pinned (determined by constraints) versus free (still available for further refinement). A closed budget means all sites are pinned and the type is fully resolved. -/
structure FreeRank (P : Primitives) where
  /-- The total number of site coordinates in this budget, equal to the quantum level n. -/
  totalSites : P.NonNegativeInteger
  /-- The number of site coordinates currently pinned by constraints. -/
  pinnedCount : P.NonNegativeInteger
  /-- The number of site coordinates still free (not yet pinned). Equals totalSites - pinnedCount. -/
  freeRank : P.NonNegativeInteger
  /-- Whether all sites in this budget are pinned. A closed budget means the type is fully resolved and the partition is complete. -/
  isClosed : P.Boolean
  /-- A site coordinate belonging to this budget. -/
  hasSite : Array (SiteIndex P)
  /-- A site pinning record in this budget. -/
  hasBinding : Array (SiteBinding P)
  /-- True when this site budget uses a reversible computation strategy preserving information through ancilla sites. -/
  reversibleStrategy : P.Boolean

/-- A record of a single site being pinned by a constraint. Links a specific site coordinate to the constraint that determined its value. -/
structure SiteBinding (P : Primitives) where
  /-- The constraint that pins this site coordinate. -/
  pinnedBy : UOR.User.Type_.Constraint P
  /-- The site coordinate that this pinning determines. -/
  pinsCoordinate : SiteIndex P

/-- The tensor product of two partitions: partition(A × B) = partition(A) ⊗ partition(B). The four-component structure combines component-wise under the product type construction (PT_2a). Carries leftFactor and rightFactor links to the operand partitions. -/
structure PartitionProduct (P : Primitives) where
  /-- The left operand partition of this tensor product. -/
  leftFactor : Partition P
  /-- The right operand partition of this tensor product. -/
  rightFactor : Partition P

/-- The coproduct (disjoint union) of two partitions: partition(A + B) = partition(A) ⊕ partition(B). The four-component structure combines via disjoint union under the sum type construction (PT_2b). Carries leftSummand and rightSummand links to the operand partitions. -/
structure PartitionCoproduct (P : Primitives) where
  /-- The left operand partition of this coproduct. -/
  leftSummand : Partition P
  /-- The right operand partition of this coproduct. -/
  rightSummand : Partition P
