-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Computation Traces namespace structures.

import UOR.Primitives
import UOR.Enums
import UOR.Bridge.Cert
import UOR.Bridge.Observable
import UOR.Kernel.Op
import UOR.Kernel.Schema

open UOR.Primitives

/-- A complete record of a kernel computation: the input, output, every operation step, and accumulated metrics. -/
structure ComputationTrace (P : Primitives) where
  /-- The input datum of this computation. -/
  input : UOR.Kernel.Schema.Datum P
  /-- The output datum of this computation. -/
  output : UOR.Kernel.Schema.Datum P
  /-- A computation step in this trace. -/
  step : Array (ComputationStep P)
  /-- The monodromy accumulated by this computation: the net dihedral group element produced by the full operation sequence. -/
  monodromy : UOR.Bridge.Observable.DihedralElement P
  /-- The certificate that attests to the correctness of this computation trace. -/
  certifiedBy : UOR.Bridge.Cert.Certificate P
  /-- The residual entropy observable remaining after this computation trace, linking to the ThermoObservable taxonomy (TH_9 connection). -/
  residualEntropy : UOR.Bridge.Observable.ResidualEntropy P
  /-- Whether this computation trace satisfies the dual geodesic condition (GD_1): AR_1-ordered and DC_10-selected. -/
  isGeodesic : P.Boolean
  /-- A GeodesicViolation record indicating where the trace deviated from the geodesic condition. -/
  geodesicViolation : Array (GeodesicViolation P)
  /-- The total entropy cost accumulated across all steps of a trace. On a geodesic, equals freeRank_initial × ln 2 (GD_3). -/
  cumulativeEntropyCost : P.Decimal
  /-- Whether the step sequence of this trace follows the AR_1 adiabatic ordering (decreasing freeRank × cost-per-site). -/
  adiabaticallyOrdered : P.Boolean
  /-- A MeasurementEvent step within this computation trace. -/
  measurementEvent : Array (MeasurementEvent P)
  /-- Whether this computation trace has steps ordered by the AR_1 adiabatic metric (decreasing freeRank × cost-per-site). One of the two sub-predicates of isGeodesic (GD_6). -/
  isAR1Ordered : P.Boolean
  /-- Whether each step of this computation trace was selected by the DC_10 Jacobian criterion (maximal J_k among free sites). One of the two sub-predicates of isGeodesic (GD_6). -/
  isDC10Selected : P.Boolean

/-- A single step in a computation trace: one operation applied to produce one output from one or more inputs. -/
structure ComputationStep (P : Primitives) where
  /-- The input datum of this computation step. -/
  from : UOR.Kernel.Schema.Datum P
  /-- The output datum of this computation step. -/
  to : UOR.Kernel.Schema.Datum P
  /-- The operation applied in this computation step. -/
  operation : UOR.Kernel.Op.Operation P
  /-- The zero-based sequential index of this step within its trace. -/
  index : P.NonNegativeInteger
  /-- The entropy cost of a single computation step. On a geodesic, this equals ln 2 for every step (GD_2). -/
  stepEntropyCost : P.Decimal
  /-- The Jacobian value J_k at this step, used by the GeodesicValidator to check DC_10 maximality. -/
  jacobianAtStep : P.Decimal

/-- Summary metrics for a computation trace: total steps, accumulated ring distance, and accumulated Hamming distance. -/
structure TraceMetrics (P : Primitives) where
  /-- Total number of computation steps in this trace. -/
  stepCount : P.NonNegativeInteger
  /-- Total ring-metric distance accumulated across all steps. -/
  totalRingDistance : P.NonNegativeInteger
  /-- Total Hamming-metric distance accumulated across all steps. -/
  totalHammingDistance : P.NonNegativeInteger

/-- A computation trace that satisfies the dual geodesic condition (GD_1): AR_1-ordered and DC_10-selected. The path of least dissipation through the resolution landscape. -/
structure GeodesicTrace (P : Primitives) extends ComputationTrace P where
  /-- The GeodesicCertificate attesting that this trace satisfied both GD_1 conditions. -/
  geodesicCertificate : UOR.Bridge.Cert.GeodesicCertificate P

/-- A record of a geodesic condition violation at a specific step of a computation trace. Produced by GeodesicValidator when J_k(step_i) < max_\{free\} J_k(state_i). -/
structure GeodesicViolation (P : Primitives) where
  /-- Human-readable description of why a geodesic violation occurred, citing the step index and the unused higher-J_k option. -/
  violationReason : P.String

/-- A specialized computation step recording a single projective collapse of a SuperposedSiteState. Carries pre-collapse entropy and post-collapse Landauer cost (QM_1). -/
structure MeasurementEvent (P : Primitives) extends ComputationStep P where
  /-- The von Neumann entropy S_vN of the SuperposedSiteState before projective collapse. -/
  preCollapseEntropy : P.Decimal
  /-- The Landauer cost incurred by the projective collapse. Equals preCollapseEntropy at β* = ln 2 (QM_1). -/
  postCollapseLandauerCost : P.Decimal
  /-- The step index within the enclosing ComputationTrace at which this projective collapse occurred. -/
  collapseStep : P.NonNegativeInteger
  /-- The full pre-collapse amplitude vector of all branches at the time of measurement. Enables Born rule verification (QM_5): P(outcome k) = |α_k|² / Σ|αᵢ|². -/
  amplitudeVector : P.Decimal

/-- A single outcome of a projective measurement on a SuperposedSiteState, recording the classical site index (outcomeValue) and its Born-rule probability |α_k|² (outcomeProbability). Multiple outcomes form the probability distribution of a measurement. -/
structure MeasurementOutcome (P : Primitives) where
  /-- The classical site index selected by projective collapse in this measurement outcome. -/
  outcomeValue : P.NonNegativeInteger
  /-- The Born-rule probability of this measurement outcome: |α_k|² where α_k is the amplitude of the collapsed site. -/
  outcomeProbability : P.Decimal


/-- Canonical geodesic trace at quantum level Q0 (n=8). Demonstrates GD_1 through GD_3 at the base level. -/
namespace geodesic_Q0
def ADIABATICALLY_ORDERED : Bool := true
def IS_GEODESIC : Bool := true
end geodesic_Q0

/-- Canonical geodesic trace at quantum level Q1 (n=16). Demonstrates geodesic scaling from Q0 to Q1. -/
namespace geodesic_Q1
def ADIABATICALLY_ORDERED : Bool := true
def IS_GEODESIC : Bool := true
end geodesic_Q1

/-- Canonical geodesic trace at quantum level Q2 (n=32). Demonstrates geodesic scaling from Q1 to Q2. -/
namespace geodesic_Q2
def ADIABATICALLY_ORDERED : Bool := true
def IS_GEODESIC : Bool := true
end geodesic_Q2

/-- Canonical geodesic trace at quantum level Q3 (n=64). Demonstrates geodesic scaling from Q2 to Q3. -/
namespace geodesic_Q3
def ADIABATICALLY_ORDERED : Bool := true
def IS_GEODESIC : Bool := true
end geodesic_Q3

/-- Canonical measurement event: collapse of an equal superposition (|α|² = 0.5). Maximum von Neumann entropy S_vN = ln 2. Maximum Landauer cost per QM_1. -/
namespace collapse_equal_superposition
def POST_COLLAPSE_LANDAUER_COST : String := "0.693147"
def PRE_COLLAPSE_ENTROPY : String := "0.693147"
end collapse_equal_superposition

/-- Canonical measurement event: collapse of a biased superposition (|α|² = 0.9). Lower entropy than equal superposition. Demonstrates QM_3 bound. -/
namespace collapse_biased
def POST_COLLAPSE_LANDAUER_COST : String := "0.325083"
def PRE_COLLAPSE_ENTROPY : String := "0.325083"
end collapse_biased

/-- Canonical measurement event: collapse of a classical state (|α|² = 1). Zero entropy, zero Landauer cost. Demonstrates QM_4 idempotence. -/
namespace collapse_classical
def POST_COLLAPSE_LANDAUER_COST : String := "0.0"
def PRE_COLLAPSE_ENTROPY : String := "0.0"
end collapse_classical
