// @generated by uor-crate from uor-ontology — do not edit manually

//! `division/` namespace — The four normed division algebras R, C, H, O and the Cayley-Dickson construction..
//!
//! Space: Kernel

use crate::HostTypes;

/// An algebra over R that is a division ring with multiplicative norm. Exactly four exist (Hurwitz theorem): R, C, H, O.
pub trait NormedDivisionAlgebra<H: HostTypes> {
    /// The dimension of this division algebra (1, 2, 4, or 8).
    fn algebra_dimension(&self) -> u64;
    /// Whether multiplication in this algebra is commutative.
    fn is_commutative(&self) -> bool;
    /// Whether multiplication in this algebra is associative.
    fn is_associative(&self) -> bool;
    /// The basis elements of this division algebra.
    fn basis_elements(&self) -> &H::HostString;
    /// Associated type for `MultiplicationTable`.
    type MultiplicationTable: MultiplicationTable<H>;
    /// The multiplication table for this algebra.
    fn algebra_multiplication_table(&self) -> &Self::MultiplicationTable;
}

/// The doubling construction that builds each division algebra from the previous: R → C → H → O.
pub trait CayleyDicksonConstruction<H: HostTypes> {
    /// Associated type for `NormedDivisionAlgebra`.
    type NormedDivisionAlgebra: NormedDivisionAlgebra<H>;
    /// The source algebra of the Cayley-Dickson doubling.
    fn cayley_dickson_source(&self) -> &Self::NormedDivisionAlgebra;
    /// The target algebra of the Cayley-Dickson doubling.
    fn cayley_dickson_target(&self) -> &Self::NormedDivisionAlgebra;
    /// The new basis element adjoined by this doubling step.
    fn adjoined_element(&self) -> &H::HostString;
    /// The conjugation and multiplication rule for the adjoined element.
    fn conjugation_rule(&self) -> &H::HostString;
}

/// The explicit product rules for a division algebra’s basis elements.
pub trait MultiplicationTable<H: HostTypes> {}

/// The commutator \[a,b\] = ab − ba. Zero for R and C; non-zero for H and O.
pub trait AlgebraCommutator<H: HostTypes> {}

/// The associator \[a,b,c\] = (ab)c − a(bc). Zero for R, C, H; non-zero for O.
pub trait AlgebraAssociator<H: HostTypes> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `NormedDivisionAlgebra<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullNormedDivisionAlgebra<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullNormedDivisionAlgebra<H> {
    fn default() -> Self { Self { _phantom: core::marker::PhantomData } }
}
impl<H: HostTypes> NullNormedDivisionAlgebra<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullNormedDivisionAlgebra<H> = NullNormedDivisionAlgebra { _phantom: core::marker::PhantomData };
}
impl<H: HostTypes> NormedDivisionAlgebra<H> for NullNormedDivisionAlgebra<H> {
    fn algebra_dimension(&self) -> u64 { 0 }
    fn is_commutative(&self) -> bool { false }
    fn is_associative(&self) -> bool { false }
    fn basis_elements(&self) -> &H::HostString { H::EMPTY_HOST_STRING }
    type MultiplicationTable = NullMultiplicationTable<H>;
    fn algebra_multiplication_table(&self) -> &Self::MultiplicationTable { &<NullMultiplicationTable<H>>::ABSENT }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `CayleyDicksonConstruction<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullCayleyDicksonConstruction<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullCayleyDicksonConstruction<H> {
    fn default() -> Self { Self { _phantom: core::marker::PhantomData } }
}
impl<H: HostTypes> NullCayleyDicksonConstruction<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullCayleyDicksonConstruction<H> = NullCayleyDicksonConstruction { _phantom: core::marker::PhantomData };
}
impl<H: HostTypes> CayleyDicksonConstruction<H> for NullCayleyDicksonConstruction<H> {
    type NormedDivisionAlgebra = NullNormedDivisionAlgebra<H>;
    fn cayley_dickson_source(&self) -> &Self::NormedDivisionAlgebra { &<NullNormedDivisionAlgebra<H>>::ABSENT }
    fn cayley_dickson_target(&self) -> &Self::NormedDivisionAlgebra { &<NullNormedDivisionAlgebra<H>>::ABSENT }
    fn adjoined_element(&self) -> &H::HostString { H::EMPTY_HOST_STRING }
    fn conjugation_rule(&self) -> &H::HostString { H::EMPTY_HOST_STRING }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `MultiplicationTable<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullMultiplicationTable<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullMultiplicationTable<H> {
    fn default() -> Self { Self { _phantom: core::marker::PhantomData } }
}
impl<H: HostTypes> NullMultiplicationTable<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullMultiplicationTable<H> = NullMultiplicationTable { _phantom: core::marker::PhantomData };
}
impl<H: HostTypes> MultiplicationTable<H> for NullMultiplicationTable<H> {
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `AlgebraCommutator<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullAlgebraCommutator<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullAlgebraCommutator<H> {
    fn default() -> Self { Self { _phantom: core::marker::PhantomData } }
}
impl<H: HostTypes> NullAlgebraCommutator<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullAlgebraCommutator<H> = NullAlgebraCommutator { _phantom: core::marker::PhantomData };
}
impl<H: HostTypes> AlgebraCommutator<H> for NullAlgebraCommutator<H> {
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `AlgebraAssociator<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullAlgebraAssociator<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullAlgebraAssociator<H> {
    fn default() -> Self { Self { _phantom: core::marker::PhantomData } }
}
impl<H: HostTypes> NullAlgebraAssociator<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullAlgebraAssociator<H> = NullAlgebraAssociator { _phantom: core::marker::PhantomData };
}
impl<H: HostTypes> AlgebraAssociator<H> for NullAlgebraAssociator<H> {
}

/// The real numbers R: dimension 1, commutative, associative.
pub mod real_algebra {
    /// `algebraDimension`
    pub const ALGEBRA_DIMENSION: i64 = 1;
    /// `basisElements`
    pub const BASIS_ELEMENTS: &str = "{1}";
    /// `isAssociative`
    pub const IS_ASSOCIATIVE: bool = true;
    /// `isCommutative`
    pub const IS_COMMUTATIVE: bool = true;
}

/// The complex numbers C: dimension 2, commutative, associative.
pub mod complex_algebra {
    /// `algebraDimension`
    pub const ALGEBRA_DIMENSION: i64 = 2;
    /// `basisElements`
    pub const BASIS_ELEMENTS: &str = "{1, i}";
    /// `isAssociative`
    pub const IS_ASSOCIATIVE: bool = true;
    /// `isCommutative`
    pub const IS_COMMUTATIVE: bool = true;
}

/// The quaternions H: dimension 4, non-commutative, associative.
pub mod quaternion_algebra {
    /// `algebraDimension`
    pub const ALGEBRA_DIMENSION: i64 = 4;
    /// `basisElements`
    pub const BASIS_ELEMENTS: &str = "{1, i, j, k}";
    /// `isAssociative`
    pub const IS_ASSOCIATIVE: bool = true;
    /// `isCommutative`
    pub const IS_COMMUTATIVE: bool = false;
}

/// The octonions O: dimension 8, non-commutative, non-associative.
pub mod octonion_algebra {
    /// `algebraDimension`
    pub const ALGEBRA_DIMENSION: i64 = 8;
    /// `basisElements`
    pub const BASIS_ELEMENTS: &str = "{1, i, j, k, l, il, jl, kl}";
    /// `isAssociative`
    pub const IS_ASSOCIATIVE: bool = false;
    /// `isCommutative`
    pub const IS_COMMUTATIVE: bool = false;
}

/// Cayley-Dickson doubling R → C: adjoin i with i² = −1.
pub mod cayley_dickson_r_to_c {
    /// `adjoinedElement`
    pub const ADJOINED_ELEMENT: &str = "i";
    /// `cayleyDicksonSource` -> `RealAlgebra`
    pub const CAYLEY_DICKSON_SOURCE: &str = "https://uor.foundation/division/RealAlgebra";
    /// `cayleyDicksonTarget` -> `ComplexAlgebra`
    pub const CAYLEY_DICKSON_TARGET: &str = "https://uor.foundation/division/ComplexAlgebra";
    /// `conjugationRule`
    pub const CONJUGATION_RULE: &str = "i² = −1";
}

/// Cayley-Dickson doubling C → H: adjoin j with j² = −1, ij = k, ji = −k.
pub mod cayley_dickson_c_to_h {
    /// `adjoinedElement`
    pub const ADJOINED_ELEMENT: &str = "j";
    /// `cayleyDicksonSource` -> `ComplexAlgebra`
    pub const CAYLEY_DICKSON_SOURCE: &str = "https://uor.foundation/division/ComplexAlgebra";
    /// `cayleyDicksonTarget` -> `QuaternionAlgebra`
    pub const CAYLEY_DICKSON_TARGET: &str = "https://uor.foundation/division/QuaternionAlgebra";
    /// `conjugationRule`
    pub const CONJUGATION_RULE: &str = "ij = k, ji = −k";
}

/// Cayley-Dickson doubling H → O: adjoin l, non-associative Fano plane products.
pub mod cayley_dickson_h_to_o {
    /// `adjoinedElement`
    pub const ADJOINED_ELEMENT: &str = "l";
    /// `cayleyDicksonSource` -> `QuaternionAlgebra`
    pub const CAYLEY_DICKSON_SOURCE: &str = "https://uor.foundation/division/QuaternionAlgebra";
    /// `cayleyDicksonTarget` -> `OctonionAlgebra`
    pub const CAYLEY_DICKSON_TARGET: &str = "https://uor.foundation/division/OctonionAlgebra";
    /// `conjugationRule`
    pub const CONJUGATION_RULE: &str = "non-associative Fano plane products";
}
