// @generated by uor-crate from uor-ontology — do not edit manually

//! `region/` namespace — Spatial locality of content-addressed ring elements. Defines computable working sets for resolver stages, independent of physical memory layout..
//!
//! Space: Kernel

use crate::enums::MeasurementUnit;
use crate::HostTypes;

/// A contiguous range of u:Element values accessible during a single reduction step. Defines the resolver’s working set.
pub trait AddressRegion<H: HostTypes> {
    /// Associated type for `RegionBound`.
    type RegionBound: RegionBound<H>;
    /// The boundary of this region.
    fn region_bound(&self) -> &Self::RegionBound;
    /// Associated type for `LocalityMetric`.
    type LocalityMetric: LocalityMetric<H>;
    /// The metric defining contiguity for this region.
    fn locality_metric(&self) -> &Self::LocalityMetric;
    /// Number of addresses in this region.
    fn region_cardinality(&self) -> u64;
}

/// The boundary of an AddressRegion: a pair (lowerAddress, upperAddress) in the content-address ordering.
pub trait RegionBound<H: HostTypes> {
    /// Associated type for `Element`.
    type Element: crate::kernel::address::Element<H>;
    /// The lower bound of the address range.
    fn region_lower(&self) -> &Self::Element;
    /// The upper bound of the address range.
    fn region_upper(&self) -> &Self::Element;
}

/// A metric on u:Element values determining which addresses are near each other for resolution purposes.
pub trait LocalityMetric<H: HostTypes>: crate::bridge::observable::MetricObservable<H> {}

/// The set of AddressRegions needed by a resolver at a specific reduction step for a specific type. Computable from the type’s constraint nerve.
pub trait WorkingSet<H: HostTypes> {
    /// Associated type for `AddressRegion`.
    type AddressRegion: AddressRegion<H>;
    /// The address regions composing this working set.
    fn working_set_regions(&self) -> &[Self::AddressRegion];
    /// Associated type for `ReductionStep`.
    type ReductionStep: crate::kernel::reduction::ReductionStep<H>;
    /// The reduction step this working set applies to.
    fn working_set_stage(&self) -> &Self::ReductionStep;
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: crate::user::type_::TypeDefinition<H>;
    /// The type being resolved.
    fn working_set_type(&self) -> &Self::TypeDefinition;
    /// Total addresses across all regions in the working set.
    fn working_set_size(&self) -> u64;
}

/// An assignment of AddressRegions to reduction steps for a given computation. Enables Prism to pre-compute memory layout.
pub trait RegionAllocation<H: HostTypes> {
    /// Associated type for `ReductionStep`.
    type ReductionStep: crate::kernel::reduction::ReductionStep<H>;
    /// Reduction steps in this allocation.
    fn allocation_stage(&self) -> &[Self::ReductionStep];
    /// Associated type for `WorkingSet`.
    type WorkingSet: WorkingSet<H>;
    /// The working sets assigned to each stage.
    fn allocation_working_set(&self) -> &[Self::WorkingSet];
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `AddressRegion<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullAddressRegion<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullAddressRegion<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullAddressRegion<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullAddressRegion<H> = NullAddressRegion {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> AddressRegion<H> for NullAddressRegion<H> {
    type RegionBound = NullRegionBound<H>;
    fn region_bound(&self) -> &Self::RegionBound {
        &<NullRegionBound<H>>::ABSENT
    }
    type LocalityMetric = NullLocalityMetric<H>;
    fn locality_metric(&self) -> &Self::LocalityMetric {
        &<NullLocalityMetric<H>>::ABSENT
    }
    fn region_cardinality(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `RegionBound<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullRegionBound<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullRegionBound<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullRegionBound<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullRegionBound<H> = NullRegionBound {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> RegionBound<H> for NullRegionBound<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn region_lower(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
    fn region_upper(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `LocalityMetric<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullLocalityMetric<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullLocalityMetric<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullLocalityMetric<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullLocalityMetric<H> = NullLocalityMetric {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> crate::bridge::observable::Observable<H> for NullLocalityMetric<H> {
    fn value(&self) -> H::Decimal {
        H::EMPTY_DECIMAL
    }
    fn source(&self) -> &H::HostString {
        H::EMPTY_HOST_STRING
    }
    fn target(&self) -> &H::HostString {
        H::EMPTY_HOST_STRING
    }
    fn has_unit(&self) -> MeasurementUnit {
        <MeasurementUnit>::default()
    }
}
impl<H: HostTypes> crate::bridge::observable::MetricObservable<H> for NullLocalityMetric<H> {}
impl<H: HostTypes> LocalityMetric<H> for NullLocalityMetric<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `WorkingSet<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullWorkingSet<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullWorkingSet<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullWorkingSet<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullWorkingSet<H> = NullWorkingSet {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> WorkingSet<H> for NullWorkingSet<H> {
    type AddressRegion = NullAddressRegion<H>;
    fn working_set_regions(&self) -> &[Self::AddressRegion] {
        &[]
    }
    type ReductionStep = crate::kernel::reduction::NullReductionStep<H>;
    fn working_set_stage(&self) -> &Self::ReductionStep {
        &<crate::kernel::reduction::NullReductionStep<H>>::ABSENT
    }
    type TypeDefinition = crate::user::type_::NullTypeDefinition<H>;
    fn working_set_type(&self) -> &Self::TypeDefinition {
        &<crate::user::type_::NullTypeDefinition<H>>::ABSENT
    }
    fn working_set_size(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `RegionAllocation<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullRegionAllocation<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullRegionAllocation<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullRegionAllocation<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullRegionAllocation<H> = NullRegionAllocation {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> RegionAllocation<H> for NullRegionAllocation<H> {
    type ReductionStep = crate::kernel::reduction::NullReductionStep<H>;
    fn allocation_stage(&self) -> &[Self::ReductionStep] {
        &[]
    }
    type WorkingSet = NullWorkingSet<H>;
    fn allocation_working_set(&self) -> &[Self::WorkingSet] {
        &[]
    }
}
