//! Lean 4 source code emitter.
//!
//! Builds up Lean source files as strings and writes them to disk.

use std::fmt::Write as FmtWrite;
use std::path::Path;

use anyhow::{Context, Result};

/// A builder for a single Lean 4 source file.
pub struct LeanFile {
    /// The internal buffer. Public for `writeln!` usage in sibling modules.
    pub buf: String,
}

impl LeanFile {
    /// Creates a new Lean file with the `@generated` header.
    pub fn new(module_doc: &str) -> Self {
        let mut buf = String::with_capacity(4096);
        buf.push_str("-- @generated by uor-lean from uor-ontology \u{2014} do not edit manually\n");
        if !module_doc.is_empty() {
            buf.push_str("--\n");
            let _ = writeln!(buf, "-- {module_doc}");
        }
        buf.push('\n');
        Self { buf }
    }

    /// Appends a raw line.
    pub fn line(&mut self, s: &str) {
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    /// Appends a blank line.
    pub fn blank(&mut self) {
        self.buf.push('\n');
    }

    /// Appends a Lean 4 doc comment (`/-- ... -/`).
    pub fn doc_comment(&mut self, comment: &str) {
        let normalized = normalize_lean_comment(comment);
        let _ = writeln!(self.buf, "/-- {normalized} -/");
    }

    /// Appends an indented Lean 4 doc comment (2 spaces, for inside structure bodies).
    pub fn indented_doc_comment(&mut self, comment: &str) {
        let normalized = normalize_lean_comment(comment);
        let _ = writeln!(self.buf, "  /-- {normalized} -/");
    }

    /// Returns the built source as a string, with trailing whitespace trimmed.
    pub fn finish(self) -> String {
        let trimmed = self.buf.trim_end();
        format!("{trimmed}\n")
    }
}

/// Writes a Lean source file to disk, creating parent directories as needed.
///
/// # Errors
///
/// Returns an error if the directory cannot be created or the file cannot be written.
pub fn write_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }
    std::fs::write(path, content)
        .with_context(|| format!("Failed to write: {}", path.display()))?;
    Ok(())
}

/// Normalizes a comment string for Lean 4 doc comments: collapses internal
/// whitespace runs and escapes Lean comment delimiters.
pub fn normalize_lean_comment(s: &str) -> String {
    let collapsed: String = s.split_whitespace().collect::<Vec<_>>().join(" ");
    // Break /- and -/ sequences with a space to prevent nested comment issues
    collapsed.replace("/-", "/ -").replace("-/", "- /")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn comment_delimiter_escaping() {
        assert_eq!(normalize_lean_comment("foo /- bar"), "foo / - bar");
        assert_eq!(normalize_lean_comment("foo -/ bar"), "foo - / bar");
    }

    #[test]
    fn whitespace_collapsing() {
        assert_eq!(normalize_lean_comment("a  b   c"), "a b c");
        assert_eq!(normalize_lean_comment("a\nb\tc"), "a b c");
    }

    #[test]
    fn generated_header() {
        let f = LeanFile::new("Test module.");
        let content = f.finish();
        assert!(content.starts_with("-- @generated by uor-lean"));
        assert!(content.contains("Test module."));
    }
}
