//! `op/` namespace — Ring operations, involutions, identities, and the dihedral group.
//!
//! The `op/` namespace defines the primitive operations of the UOR kernel:
//! - **Amendments 1**: 10 named operation individuals
//! - **Amendment 3**: `op:Identity` class and `op:criticalIdentity` individual
//! - **Amendment 4**: `op:Group`, `op:DihedralGroup` classes and `op:D2n` individual
//!
//! **Critical identity:** `neg(bnot(x)) = succ(x)` for all x in R_n.
//!
//! **Space classification:** `kernel` — compiled into ROM.

use crate::model::{Class, Individual, IndividualValue, Namespace, NamespaceModule, Property, PropertyKind, Space};
use crate::model::iris::*;

/// Returns the `op/` namespace module.
#[must_use]
pub fn module() -> NamespaceModule {
    NamespaceModule {
        namespace: Namespace {
            prefix: "op",
            iri: NS_OP,
            label: "UOR Operations",
            comment: "Ring operations, involutions, algebraic identities, and the \
                      dihedral symmetry group D_{2^n} generated by neg and bnot.",
            space: Space::Kernel,
            imports: &[NS_SCHEMA],
        },
        classes: classes(),
        properties: properties(),
        individuals: individuals(),
    }
}

fn classes() -> Vec<Class> {
    vec![
        Class {
            id: "https://uor.foundation/op/Operation",
            label: "Operation",
            comment: "An operation on the ring Z/(2^n)Z. The root class for all \
                      UOR kernel operations.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/op/UnaryOp",
            label: "UnaryOp",
            comment: "A unary operation on the ring: takes one datum and produces \
                      one datum.",
            subclass_of: &["https://uor.foundation/op/Operation"],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/op/BinaryOp",
            label: "BinaryOp",
            comment: "A binary operation on the ring: takes two datums and produces \
                      one datum.",
            subclass_of: &["https://uor.foundation/op/Operation"],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/op/Involution",
            label: "Involution",
            comment: "A unary operation f such that f(f(x)) = x for all x in R_n. \
                      The two UOR involutions are neg (ring reflection) and bnot \
                      (hypercube reflection).",
            subclass_of: &["https://uor.foundation/op/UnaryOp"],
            disjoint_with: &[],
        },
        // Amendment 3: Identity class
        Class {
            id: "https://uor.foundation/op/Identity",
            label: "Identity",
            comment: "An algebraic identity: a statement that two expressions are \
                      equal for all inputs. The critical identity is \
                      neg(bnot(x)) = succ(x) for all x in R_n.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        // Amendment 4: Group classes
        Class {
            id: "https://uor.foundation/op/Group",
            label: "Group",
            comment: "A group: a set with an associative binary operation, an \
                      identity element, and inverses for every element.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/op/DihedralGroup",
            label: "DihedralGroup",
            comment: "The dihedral group D_{2^n} of order 2^(n+1), generated by the \
                      ring reflection (neg) and the hypercube reflection (bnot). \
                      This group governs the symmetry of the UOR type space.",
            subclass_of: &["https://uor.foundation/op/Group"],
            disjoint_with: &[],
        },
    ]
}

fn properties() -> Vec<Property> {
    vec![
        Property {
            id: "https://uor.foundation/op/arity",
            label: "arity",
            comment: "The number of arguments this operation takes. 1 for unary \
                      operations, 2 for binary operations.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/Operation"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/op/geometricCharacter",
            label: "geometricCharacter",
            comment: "A description of the geometric role of this operation in the \
                      UOR ring and hypercube geometry. Examples: 'ring_reflection', \
                      'hypercube_reflection', 'rotation', 'translation', 'scaling'.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/Operation"),
            range: XSD_STRING,
        },
        Property {
            id: "https://uor.foundation/op/commutative",
            label: "commutative",
            comment: "Whether this binary operation satisfies op(x,y) = op(y,x) \
                      for all x, y in R_n.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/BinaryOp"),
            range: XSD_BOOLEAN,
        },
        Property {
            id: "https://uor.foundation/op/associative",
            label: "associative",
            comment: "Whether this binary operation satisfies \
                      op(op(x,y),z) = op(x,op(y,z)) for all x, y, z in R_n.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/BinaryOp"),
            range: XSD_BOOLEAN,
        },
        Property {
            id: "https://uor.foundation/op/identity",
            label: "identity",
            comment: "The identity element of this binary operation: the value e \
                      such that op(x, e) = op(e, x) = x for all x in R_n.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/BinaryOp"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/op/inverse",
            label: "inverse",
            comment: "The inverse operation: the operation inv_op such that \
                      op(x, inv_op(x)) = e for all x, where e is the identity.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/op/Operation"),
            range: "https://uor.foundation/op/Operation",
        },
        // Amendment 1: composedOf property
        Property {
            id: "https://uor.foundation/op/composedOf",
            label: "composedOf",
            comment: "Ordered list of operations this operation is composed from. \
                      Uses rdf:List to preserve application order (first element \
                      applied innermost). E.g., succ = neg ∘ bnot is encoded as \
                      [op:neg, op:bnot] meaning neg applied to the result of bnot.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/op/Operation"),
            range: RDF_LIST,
        },
        // Amendment 3: Identity properties
        Property {
            id: "https://uor.foundation/op/lhs",
            label: "lhs",
            comment: "The left-hand side operation of an algebraic identity.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/op/Identity"),
            range: "https://uor.foundation/op/Operation",
        },
        Property {
            id: "https://uor.foundation/op/rhs",
            label: "rhs",
            comment: "The right-hand side operation of an algebraic identity.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/op/Identity"),
            range: "https://uor.foundation/op/Operation",
        },
        Property {
            id: "https://uor.foundation/op/forAll",
            label: "forAll",
            comment: "The quantifier scope: the variable(s) over which this \
                      algebraic identity holds (e.g., 'x ∈ R_n').",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/Identity"),
            range: XSD_STRING,
        },
        // Amendment 4: Group properties
        Property {
            id: "https://uor.foundation/op/generatedBy",
            label: "generatedBy",
            comment: "An operation that generates this group. The dihedral group \
                      D_{2^n} is generated by op:neg and op:bnot.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/op/Group"),
            range: "https://uor.foundation/op/Operation",
        },
        Property {
            id: "https://uor.foundation/op/order",
            label: "order",
            comment: "The number of elements in the group. For D_{2^n}, the order \
                      is 2^(n+1).",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/op/Group"),
            range: XSD_POSITIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/op/presentation",
            label: "presentation",
            comment: "The group presentation (generators and relations). \
                      Annotation only — not used for reasoning. \
                      Example: ⟨r, s | r^{2^n} = s² = e, srs = r⁻¹⟩",
            kind: PropertyKind::Annotation,
            functional: true,
            domain: Some("https://uor.foundation/op/Group"),
            range: XSD_STRING,
        },
    ]
}

fn individuals() -> Vec<Individual> {
    vec![
        // Amendment 1: 10 primitive operation individuals
        Individual {
            id: "https://uor.foundation/op/neg",
            type_: "https://uor.foundation/op/Involution",
            label: "neg",
            comment: "Ring reflection: neg(x) = (-x) mod 2^n. One of the two \
                      generators of the dihedral group D_{2^n}. neg(neg(x)) = x \
                      (involution property).",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(1)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("ring_reflection")),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/bnot",
            type_: "https://uor.foundation/op/Involution",
            label: "bnot",
            comment: "Hypercube reflection: bnot(x) = (2^n - 1) ⊕ x (bitwise complement). \
                      The second generator of D_{2^n}. bnot(bnot(x)) = x.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(1)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("hypercube_reflection")),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/succ",
            type_: "https://uor.foundation/op/UnaryOp",
            label: "succ",
            comment: "Successor: succ(x) = neg(bnot(x)) = (x + 1) mod 2^n. \
                      The critical identity: succ is the composition neg ∘ bnot.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(1)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("rotation")),
                ("https://uor.foundation/op/composedOf", IndividualValue::List(&[
                    "https://uor.foundation/op/neg",
                    "https://uor.foundation/op/bnot",
                ])),
                ("https://uor.foundation/op/inverse", IndividualValue::IriRef("https://uor.foundation/op/pred")),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/pred",
            type_: "https://uor.foundation/op/UnaryOp",
            label: "pred",
            comment: "Predecessor: pred(x) = bnot(neg(x)) = (x - 1) mod 2^n. \
                      The inverse of succ. pred is the composition bnot ∘ neg.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(1)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("rotation_inverse")),
                ("https://uor.foundation/op/composedOf", IndividualValue::List(&[
                    "https://uor.foundation/op/bnot",
                    "https://uor.foundation/op/neg",
                ])),
                ("https://uor.foundation/op/inverse", IndividualValue::IriRef("https://uor.foundation/op/succ")),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/add",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "add",
            comment: "Ring addition: add(x, y) = (x + y) mod 2^n. \
                      Commutative, associative; identity element is 0.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("translation")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/identity", IndividualValue::Int(0)),
                ("https://uor.foundation/op/inverse", IndividualValue::IriRef("https://uor.foundation/op/sub")),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/sub",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "sub",
            comment: "Ring subtraction: sub(x, y) = (x - y) mod 2^n. \
                      Not commutative, not associative.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("translation")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(false)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(false)),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/mul",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "mul",
            comment: "Ring multiplication: mul(x, y) = (x × y) mod 2^n. \
                      Commutative, associative; identity element is 1.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("scaling")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/identity", IndividualValue::Int(1)),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/xor",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "xor",
            comment: "Bitwise exclusive or: xor(x, y) = x ⊕ y. \
                      Commutative, associative; identity element is 0.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("hypercube_translation")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/identity", IndividualValue::Int(0)),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/and",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "and",
            comment: "Bitwise and: and(x, y) = x ∧ y. \
                      Commutative, associative.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("hypercube_projection")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(true)),
            ],
        },
        Individual {
            id: "https://uor.foundation/op/or",
            type_: "https://uor.foundation/op/BinaryOp",
            label: "or",
            comment: "Bitwise or: or(x, y) = x ∨ y. \
                      Commutative, associative.",
            properties: &[
                ("https://uor.foundation/op/arity", IndividualValue::Int(2)),
                ("https://uor.foundation/op/geometricCharacter", IndividualValue::Str("hypercube_join")),
                ("https://uor.foundation/op/commutative", IndividualValue::Bool(true)),
                ("https://uor.foundation/op/associative", IndividualValue::Bool(true)),
            ],
        },
        // Amendment 3: criticalIdentity individual
        Individual {
            id: "https://uor.foundation/op/criticalIdentity",
            type_: "https://uor.foundation/op/Identity",
            label: "Critical Identity",
            comment: "The foundational theorem of the UOR kernel: \
                      neg(bnot(x)) = succ(x) for all x in R_n. \
                      This identity links the two involutions (neg and bnot) to the \
                      successor operation, making succ derivable from neg and bnot.",
            properties: &[
                ("https://uor.foundation/op/lhs", IndividualValue::IriRef("https://uor.foundation/op/succ")),
                ("https://uor.foundation/op/rhs", IndividualValue::IriRef("https://uor.foundation/op/neg")),
                ("https://uor.foundation/op/forAll", IndividualValue::Str("x ∈ R_n")),
            ],
        },
        // Amendment 4: D2n individual
        Individual {
            id: "https://uor.foundation/op/D2n",
            type_: "https://uor.foundation/op/DihedralGroup",
            label: "D_{2^n}",
            comment: "The dihedral group of order 2^(n+1), generated by neg (ring \
                      reflection) and bnot (hypercube reflection). Every element of \
                      this group acts as an isometry on the type space 𝒯_n.",
            properties: &[
                ("https://uor.foundation/op/generatedBy", IndividualValue::IriRef("https://uor.foundation/op/neg")),
                ("https://uor.foundation/op/presentation", IndividualValue::Str("⟨r, s | r^{2^n} = s² = e, srs = r⁻¹⟩")),
            ],
        },
    ]
}
