// @generated by uor-crate from uor-ontology — do not edit manually

//! `observable/` namespace — Observable quantities and metrics computed by the UOR kernel. Includes ring-metric, Hamming-metric, curvature, holonomy, and catastrophe-theoretic observables..
//!
//! Space: Bridge

use crate::Primitives;

/// A measurable quantity in the UOR Framework. All observables are kernel-computed and user-consumed.
pub trait Observable<P: Primitives> {
    /// The numeric value of an observable measurement.
    fn value(&self) -> P::Decimal;
    /// The unit of measurement for this observable (e.g., 'bits', 'ring_steps', 'dimensionless').
    fn unit(&self) -> &P::String;
    /// The source object of this measurement (datum, partition, or path start point).
    fn source(&self) -> &P::String;
    /// The target object of this measurement (for metrics and path-end measurements).
    fn target(&self) -> &P::String;
}

/// An observable measuring stratum-level properties: position within the ring's layer structure.
pub trait StratumObservable<P: Primitives>: Observable<P> {}

/// An observable measuring geometric distance between ring elements under a specific metric.
pub trait MetricObservable<P: Primitives>: Observable<P> {}

/// An observable measuring properties of paths through the ring: path length, total variation, winding number.
pub trait PathObservable<P: Primitives>: Observable<P> {}

/// An observable measuring cascade properties: the length and count of operation sequences.
pub trait CascadeObservable<P: Primitives>: Observable<P> {}

/// An observable measuring catastrophe-theoretic properties: thresholds at which qualitative changes occur in the partition.
pub trait CatastropheObservable<P: Primitives>: Observable<P> {}

/// An observable measuring the curvature of the UOR geometry: the gap between ring-isometry and Hamming-isometry for a given transform.
pub trait CurvatureObservable<P: Primitives>: Observable<P> {}

/// An observable measuring holonomy: the accumulated transformation when traversing a closed path in the ring.
pub trait HolonomyObservable<P: Primitives>: Observable<P> {}

/// Distance between two ring elements under the ring metric: d_R(x, y) = |x - y| mod 2^n.
pub trait RingMetric<P: Primitives>: MetricObservable<P> {}

/// Distance between two ring elements under the Hamming metric: the number of bit positions where they differ.
pub trait HammingMetric<P: Primitives>: MetricObservable<P> {}

/// The metric incompatibility between two ring elements: the divergence between their ring-metric and Hamming-metric distances, measuring geometric curvature.
pub trait IncompatibilityMetric<P: Primitives>: MetricObservable<P> {}

/// The stratum index of a ring element.
pub trait StratumValue<P: Primitives>: StratumObservable<P> {}

/// The difference in stratum between two ring elements.
pub trait StratumDelta<P: Primitives>: StratumObservable<P> {}

/// The sequence of strata traversed by a path through the ring.
pub trait StratumTrajectory<P: Primitives>: StratumObservable<P> {}

/// The length of a path through the ring, measured in operation steps.
pub trait PathLength<P: Primitives>: PathObservable<P> {}

/// The total variation of a path: the sum of metric distances between consecutive elements.
pub trait TotalVariation<P: Primitives>: PathObservable<P> {}

/// The winding number of a closed path: the number of times the path wraps around the ring.
pub trait WindingNumber<P: Primitives>: PathObservable<P> {}

/// The number of operation applications in an operation cascade.
pub trait CascadeLength<P: Primitives>: CascadeObservable<P> {}

/// The number of distinct cascades in a computation.
pub trait CascadeCount<P: Primitives>: CascadeObservable<P> {}

/// A critical value at which a qualitative change occurs in the partition structure.
pub trait CatastropheThreshold<P: Primitives>: CatastropheObservable<P> {}

/// The number of catastrophe events (qualitative partition changes) in a computation.
pub trait CatastropheCount<P: Primitives>: CatastropheObservable<P> {}

/// The commutator \[f, g\](x) = f(g(x)) - g(f(x)) of two operations, measuring their non-commutativity.
pub trait Commutator<P: Primitives>: CurvatureObservable<P> {}

/// The integrated curvature over a region of type space: the total metric incompatibility accumulated.
pub trait CurvatureFlux<P: Primitives>: CurvatureObservable<P> {}

/// The monodromy of a closed path: the net transformation accumulated when traversing a loop in the type space.
pub trait Monodromy<P: Primitives>: HolonomyObservable<P> {}

/// The parallel transport of a vector along a path: the canonical lift of the path to the tangent bundle of the ring.
pub trait ParallelTransport<P: Primitives>: HolonomyObservable<P> {}

/// An element of the dihedral group D_{2^n} acting on the type space. Each dihedral element induces an isometry of 𝒯_n.
pub trait DihedralElement<P: Primitives>: HolonomyObservable<P> {}
