// @generated by uor-crate from uor-ontology — do not edit manually

//! `partition/` namespace — Irreducibility partitions produced by type resolution. A partition divides the ring into four disjoint components: Irreducible, Reducible, Units, and Exterior..
//!
//! Space: Bridge

use crate::HostTypes;

/// A four-component partition of R_n produced by resolving a type declaration. The four components — Irreducible, Reducible, Units, Exterior — are mutually disjoint and exhaustive over the carrier.
pub trait Partition<H: HostTypes> {
    /// Associated type for `IrreducibleSet`.
    type IrreducibleSet: IrreducibleSet<H>;
    /// The irreducible component of this partition.
    fn irreducibles(&self) -> &Self::IrreducibleSet;
    /// Associated type for `ReducibleSet`.
    type ReducibleSet: ReducibleSet<H>;
    /// The reducible component of this partition.
    fn reducibles(&self) -> &Self::ReducibleSet;
    /// Associated type for `UnitGroup`.
    type UnitGroup: UnitGroup<H>;
    /// The units component of this partition.
    fn units(&self) -> &Self::UnitGroup;
    /// Associated type for `Complement`.
    type Complement: Complement<H>;
    /// The exterior component of this partition.
    fn exterior(&self) -> &Self::Complement;
    /// The irreducible density of this partition: |Irr| / |A|, where A is the active carrier.
    fn density(&self) -> H::Decimal;
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: crate::user::type_::TypeDefinition<H>;
    /// The type declaration that was resolved to produce this partition.
    fn source_type(&self) -> &Self::TypeDefinition;
    /// The Witt level n at which this partition was computed. The ring has 2^n elements at this level.
    fn witt_length(&self) -> u64;
    /// Associated type for `FreeRank`.
    type FreeRank: FreeRank<H>;
    /// The site budget associated with this partition.
    fn site_budget(&self) -> &Self::FreeRank;
    /// Whether the four components of this partition are exhaustive over R_n: |Irr| + |Red| + |Unit| + |Ext| = 2^n (FPM_8). Set by the kernel after verification.
    fn is_exhaustive(&self) -> bool;
    /// Associated type for `TagSite`.
    type TagSite: TagSite<H>;
    /// The tag site distinguishing the variants of a PartitionCoproduct. Logically distinct from every data site of either operand (ST_6) and carries the ln 2 entropy quantum of ST_2.
    fn tag_site_of(&self) -> &Self::TagSite;
    /// The categorical level at which this construction is a product / coproduct. Values: 'partition_classification' (PartitionProduct, PartitionCoproduct), or 'nerve_topology' (CartesianPartitionProduct). Prevents misreading the product vs coproduct distinction across levels.
    fn product_category_level(&self) -> &H::HostString;
}

/// A single component of a partition: a set of datum values belonging to one of the four categories.
/// Disjoint with: SiteIndex, FreeRank.
pub trait Component<H: HostTypes> {
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<H>;
    /// A datum value belonging to this partition component.
    fn member(&self) -> &[Self::Datum];
    /// The number of elements in this partition component. The cardinalities of the four components must sum to 2^n.
    fn cardinality(&self) -> u64;
}

/// The set of irreducible elements under the active type: elements whose only factorizations involve units or themselves. Analogous to prime elements in a ring.
/// Disjoint with: ReducibleSet, UnitGroup, Complement.
pub trait IrreducibleSet<H: HostTypes>: Component<H> {}

/// The set of reducible non-unit elements: elements that can be expressed as a product of two or more non-unit elements.
/// Disjoint with: IrreducibleSet, UnitGroup, Complement.
pub trait ReducibleSet<H: HostTypes>: Component<H> {}

/// The set of invertible elements (units) in the carrier: elements with a multiplicative inverse. In Z/(2^n)Z, the units are the odd integers.
/// Disjoint with: IrreducibleSet, ReducibleSet, Complement.
pub trait UnitGroup<H: HostTypes>: Component<H> {}

/// Elements of R_n that fall outside the active carrier — i.e., outside the type's domain. These are ring elements that do not participate in the current type resolution.
/// Disjoint with: IrreducibleSet, ReducibleSet, UnitGroup.
pub trait Complement<H: HostTypes>: Component<H> {
    /// Associated type for `TermExpression`.
    type TermExpression: crate::kernel::schema::TermExpression<H>;
    /// The formal membership criterion for this Complement: x ∈ Ext(T) iff x ∉ carrier(T). The Complement is context-dependent on the active type T (FPM_9).
    fn exterior_criteria(&self) -> &Self::TermExpression;
}

/// A single site coordinate in the iterated Z/2Z fibration. Each site represents one binary degree of freedom in the ring's structure. The total number of sites equals the quantum level n.
/// Disjoint with: FreeRank, Component.
pub trait SiteIndex<H: HostTypes> {
    /// The zero-based position of this site coordinate within the iterated fibration. Position 0 is the least significant bit; position n-1 is the most significant.
    fn site_position(&self) -> u64;
    /// The current state of this site coordinate: 'pinned' if determined by a constraint, 'free' if still available for refinement.
    fn site_state(&self) -> u64;
    /// Associated type for `SiteIndex`.
    type SiteIndexTarget: SiteIndex<H>;
    /// An ancilla site coordinate paired with this site for reversible computation (RC_1–RC_4 ancilla model).
    fn ancilla_site(&self) -> &Self::SiteIndexTarget;
}

/// The site budget for a partition: an accounting of how many sites are pinned (determined by constraints) versus free (still available for further refinement). A closed budget means all sites are pinned and the type is fully resolved.
/// Disjoint with: SiteIndex, Component.
pub trait FreeRank<H: HostTypes> {
    /// The total number of site coordinates in this budget, equal to the quantum level n.
    fn total_sites(&self) -> u64;
    /// The number of site coordinates currently pinned by constraints.
    fn pinned_count(&self) -> u64;
    /// The number of site coordinates still free (not yet pinned). Equals totalSites - pinnedCount.
    fn free_rank(&self) -> u64;
    /// Whether all sites in this budget are pinned. A closed budget means the type is fully resolved and the partition is complete.
    fn is_closed(&self) -> bool;
    /// Associated type for `SiteIndex`.
    type SiteIndex: SiteIndex<H>;
    /// A site coordinate belonging to this budget.
    fn has_site(&self) -> &[Self::SiteIndex];
    /// Associated type for `SiteBinding`.
    type SiteBinding: SiteBinding<H>;
    /// A site pinning record in this budget.
    fn has_binding(&self) -> &[Self::SiteBinding];
    /// True when this site budget uses a reversible computation strategy preserving information through ancilla sites.
    fn reversible_strategy(&self) -> bool;
}

/// A record of a single site being pinned by a constraint. Links a specific site coordinate to the constraint that determined its value.
pub trait SiteBinding<H: HostTypes> {
    /// Associated type for `Constraint`.
    type Constraint: crate::user::type_::Constraint<H>;
    /// The constraint that pins this site coordinate.
    fn pinned_by(&self) -> &Self::Constraint;
    /// Associated type for `SiteIndex`.
    type SiteIndex: SiteIndex<H>;
    /// The site coordinate that this pinning determines.
    fn pins_coordinate(&self) -> &Self::SiteIndex;
}

/// The tensor product of two partitions: partition(A × B) = partition(A) ⊗ partition(B). The four-component structure combines component-wise under the product type construction (PT_2a). Carries leftFactor and rightFactor links to the operand partitions.
/// Disjoint with: PartitionCoproduct, CartesianPartitionProduct.
pub trait PartitionProduct<H: HostTypes> {
    /// Associated type for `Partition`.
    type Partition: Partition<H>;
    /// The left operand partition of this tensor product.
    fn left_factor(&self) -> Self::Partition;
    /// The right operand partition of this tensor product.
    fn right_factor(&self) -> Self::Partition;
}

/// The coproduct (disjoint union) of two partitions: partition(A + B) = partition(A) ⊕ partition(B). The four-component structure combines via disjoint union under the sum type construction (PT_2b). Carries leftSummand and rightSummand links to the operand partitions.
/// Disjoint with: PartitionProduct, CartesianPartitionProduct.
pub trait PartitionCoproduct<H: HostTypes> {
    /// Associated type for `Partition`.
    type Partition: Partition<H>;
    /// The left operand partition of this coproduct.
    fn left_summand(&self) -> Self::Partition;
    /// The right operand partition of this coproduct.
    fn right_summand(&self) -> Self::Partition;
}

/// The Cartesian product of partitions. Classifies the nerve topology of A ⊠ B as a simplicial product (χ multiplicative per CPT_3, Betti by Künneth per CPT_4) rather than a site-disjoint union (χ additive — PartitionProduct). Site budget is |S_A| + |S_B| per CPT_1 — the bit width of the product state space. Partition-ness is asserted via leftCartesianFactor / rightCartesianFactor (both ranged at Partition), matching the sibling pattern for PartitionProduct and PartitionCoproduct. Satisfies CPT_1–CPT_6 per this amendment.
/// Disjoint with: PartitionProduct, PartitionCoproduct.
pub trait CartesianPartitionProduct<H: HostTypes> {
    /// Associated type for `Partition`.
    type Partition: Partition<H>;
    /// The left operand partition of this Cartesian partition product.
    fn left_cartesian_factor(&self) -> Self::Partition;
    /// The right operand partition of this Cartesian partition product.
    fn right_cartesian_factor(&self) -> Self::Partition;
}

/// The distinguishing site in a PartitionCoproduct whose value (0 or 1) selects the variant. Logically, the tag is not a data site of either operand (ST_6) and carries exactly the ln 2 entropy quantum (ST_2). Its physical placement in a flat constraint layout follows the foundation layout convention: layoutTagSite = max(SITE_COUNT(A), SITE_COUNT(B)), so the tag does not collide with any inherited bookkeeping sites when operands are themselves coproducts.
pub trait TagSite<H: HostTypes>: SiteIndex<H> {
    /// The boolean value (false = 0, true = 1) assigned to a tag site. false selects the left variant of the PartitionCoproduct; true selects the right variant.
    fn tag_value(&self) -> bool;
}

/// Observes the free-rank of the partition associated with a Datum's site context, recording the count of unbound sites at the moment of observation. Used as the bound observable for the siteConstraintKind BoundConstraint.
pub trait FreeRankObservable<H: HostTypes>: crate::bridge::observable::Observable<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `Component<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullComponent<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullComponent<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullComponent<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullComponent<H> = NullComponent {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> Component<H> for NullComponent<H> {
    type Datum = crate::kernel::schema::NullDatum<H>;
    fn member(&self) -> &[Self::Datum] {
        &[]
    }
    fn cardinality(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `IrreducibleSet<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullIrreducibleSet<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullIrreducibleSet<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullIrreducibleSet<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullIrreducibleSet<H> = NullIrreducibleSet {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> Component<H> for NullIrreducibleSet<H> {
    type Datum = crate::kernel::schema::NullDatum<H>;
    fn member(&self) -> &[Self::Datum] {
        &[]
    }
    fn cardinality(&self) -> u64 {
        0
    }
}
impl<H: HostTypes> IrreducibleSet<H> for NullIrreducibleSet<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `ReducibleSet<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullReducibleSet<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullReducibleSet<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullReducibleSet<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullReducibleSet<H> = NullReducibleSet {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> Component<H> for NullReducibleSet<H> {
    type Datum = crate::kernel::schema::NullDatum<H>;
    fn member(&self) -> &[Self::Datum] {
        &[]
    }
    fn cardinality(&self) -> u64 {
        0
    }
}
impl<H: HostTypes> ReducibleSet<H> for NullReducibleSet<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `UnitGroup<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullUnitGroup<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullUnitGroup<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullUnitGroup<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullUnitGroup<H> = NullUnitGroup {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> Component<H> for NullUnitGroup<H> {
    type Datum = crate::kernel::schema::NullDatum<H>;
    fn member(&self) -> &[Self::Datum] {
        &[]
    }
    fn cardinality(&self) -> u64 {
        0
    }
}
impl<H: HostTypes> UnitGroup<H> for NullUnitGroup<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `Complement<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullComplement<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullComplement<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullComplement<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullComplement<H> = NullComplement {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> Component<H> for NullComplement<H> {
    type Datum = crate::kernel::schema::NullDatum<H>;
    fn member(&self) -> &[Self::Datum] {
        &[]
    }
    fn cardinality(&self) -> u64 {
        0
    }
}
impl<H: HostTypes> Complement<H> for NullComplement<H> {
    type TermExpression = crate::kernel::schema::NullTermExpression<H>;
    fn exterior_criteria(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `SiteIndex<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullSiteIndex<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullSiteIndex<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullSiteIndex<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullSiteIndex<H> = NullSiteIndex {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> SiteIndex<H> for NullSiteIndex<H> {
    fn site_position(&self) -> u64 {
        0
    }
    fn site_state(&self) -> u64 {
        0
    }
    type SiteIndexTarget = NullSiteIndex<H>;
    fn ancilla_site(&self) -> &Self::SiteIndexTarget {
        &<NullSiteIndex<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `TagSite<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullTagSite<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullTagSite<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullTagSite<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullTagSite<H> = NullTagSite {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> SiteIndex<H> for NullTagSite<H> {
    fn site_position(&self) -> u64 {
        0
    }
    fn site_state(&self) -> u64 {
        0
    }
    type SiteIndexTarget = NullSiteIndex<H>;
    fn ancilla_site(&self) -> &Self::SiteIndexTarget {
        &<NullSiteIndex<H>>::ABSENT
    }
}
impl<H: HostTypes> TagSite<H> for NullTagSite<H> {
    fn tag_value(&self) -> bool {
        false
    }
}

/// The irreducible component: elements that admit no non-trivial factorization within the ring.
pub mod irreducible {}

/// The reducible component: elements that factor into non-trivial parts.
pub mod reducible {}

/// The unit component: invertible elements of the ring.
pub mod units {}

/// The exterior component: elements outside the factorization domain (e.g., zero or ring-boundary values).
pub mod exterior {}
