// @generated by uor-crate from uor-ontology — do not edit manually

//! `query/` namespace — Information extraction queries. Users initiate queries; the kernel resolves them against the ring substrate..
//!
//! Space: Bridge

use crate::Primitives;

/// A request for information from the UOR kernel. The root abstraction for all query types.
pub trait Query<P: Primitives> {
    /// The type of input the query accepts.
    fn input_type(&self) -> &P::String;
    /// The type of output the query produces.
    fn output_type(&self) -> &P::String;
}

/// A query for the ring-coordinate position of a datum: its stratum, spectrum, and address within the ring geometry.
pub trait CoordinateQuery<P: Primitives>: Query<P> {
    /// Which coordinate the query extracts.
    fn coordinate(&self) -> &P::String;
}

/// A query for a metric value between two datums: ring distance, Hamming distance, or their divergence (curvature).
pub trait MetricQuery<P: Primitives>: Query<P> {}

/// A query for the canonical representation of a datum or term: its normal form under the active resolver strategy.
pub trait RepresentationQuery<P: Primitives>: Query<P> {}
