// @generated by uor-crate from uor-ontology — do not edit manually

//! `query/` namespace — Information extraction queries. Users initiate queries; the kernel resolves them against the ring substrate..
//!
//! Space: Bridge

use crate::enums::CoordinateKind;
use crate::Primitives;

/// A request for information from the UOR kernel. The root abstraction for all query types.
pub trait Query<P: Primitives> {
    /// The type of input the query accepts.
    fn input_type(&self) -> &P::String;
    /// The type of output the query produces.
    fn output_type(&self) -> &P::String;
}

/// A query for the ring-coordinate position of a datum: its stratum, spectrum, and address within the ring geometry.
pub trait CoordinateQuery<P: Primitives>: Query<P> {
    /// The typed coordinate kind this query extracts. Replaces the string-valued query:coordinate property with a typed reference to a CoordinateKind individual.
    fn has_coordinate_kind(&self) -> CoordinateKind;
}

/// A query for a metric value between two datums: ring distance, Hamming distance, or their divergence (curvature).
pub trait MetricQuery<P: Primitives>: Query<P> {}

/// A query for the canonical representation of a datum or term: its normal form under the active resolver strategy.
pub trait RepresentationQuery<P: Primitives>: Query<P> {}

/// The stratum coordinate: the layer position of a datum within the ring's stratification.
pub mod stratum_coordinate {}

/// The spectrum coordinate: the spectral decomposition of a datum under the ring's Fourier analysis.
pub mod spectrum_coordinate {}

/// The address coordinate: the content-addressable position of a datum in the Braille glyph encoding.
pub mod address_coordinate {}
