// @generated by uor-crate from uor-ontology — do not edit manually

//! `trace/` namespace — Execution traces recording the sequence of kernel operations, intermediate results, and accumulated metrics for a computation..
//!
//! Space: Bridge

use crate::Primitives;

/// A complete record of a kernel computation: the input, output, every operation step, and accumulated metrics.
pub trait ComputationTrace<P: Primitives> {
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<P>;
    /// The input datum of this computation.
    fn input(&self) -> &Self::Datum;
    /// The output datum of this computation.
    fn output(&self) -> &Self::Datum;
    /// Associated type for `ComputationStep`.
    type ComputationStep: ComputationStep<P>;
    /// A computation step in this trace.
    fn step(&self) -> &[Self::ComputationStep];
    /// Associated type for `DihedralElement`.
    type DihedralElement: crate::bridge::observable::DihedralElement<P>;
    /// The monodromy accumulated by this computation: the net dihedral group element produced by the full operation sequence.
    fn monodromy(&self) -> &Self::DihedralElement;
    /// Associated type for `Certificate`.
    type Certificate: crate::bridge::cert::Certificate<P>;
    /// The certificate that attests to the correctness of this computation trace.
    fn certified_by(&self) -> &Self::Certificate;
}

/// A single step in a computation trace: one operation applied to produce one output from one or more inputs.
pub trait ComputationStep<P: Primitives> {
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<P>;
    /// The input datum of this computation step.
    fn from(&self) -> &Self::Datum;
    /// The output datum of this computation step.
    fn to(&self) -> &Self::Datum;
    /// Associated type for `Operation`.
    type Operation: crate::kernel::op::Operation<P>;
    /// The operation applied in this computation step.
    fn operation(&self) -> &Self::Operation;
    /// The zero-based sequential index of this step within its trace.
    fn index(&self) -> P::NonNegativeInteger;
}

/// Summary metrics for a computation trace: total steps, accumulated ring distance, and accumulated Hamming distance.
pub trait TraceMetrics<P: Primitives> {
    /// Total number of computation steps in this trace.
    fn step_count(&self) -> P::NonNegativeInteger;
    /// Total ring-metric distance accumulated across all steps.
    fn total_ring_distance(&self) -> P::NonNegativeInteger;
    /// Total Hamming-metric distance accumulated across all steps.
    fn total_hamming_distance(&self) -> P::NonNegativeInteger;
}
