-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Lean 4 formalization root.

import UOR.Primitives
import UOR.Enums
import UOR.Kernel
import UOR.Bridge
import UOR.User
