//! v0.2.1 Phase 7c.3: macros crate build script.
//!
//! Reads the UOR Foundation ontology at build time and writes three
//! OUT_DIR artifacts the macros crate `include!`s:
//!
//!   - `defaults.rs` — constants like `RESIDUE_DEFAULT_MODULUS`, sourced
//!     from `type:ConstraintDefaults` individuals. No literal 256 appears
//!     in the hand-written derive macro.
//!
//!   - `keywords.rs` — `KNOWN_KEYWORDS` list, sourced from
//!     `conformance:Shape` individuals' `surfaceForm` properties. Adding
//!     a new declaration form to the ontology regenerates this list and
//!     the `uor_ground!` parser accepts the new keyword automatically.
//!
//!   - `shape_requirements.rs` — `SHAPE_REQUIRED_KEYS` table mapping each
//!     declaration keyword (e.g., `"compile_unit"`) to the ordered list of
//!     body keys that `uor_ground!` must see. Sourced from each shape's
//!     `requiredProperty` -> `surfaceKeyword` chain.
//!
//! If any ontology edit invalidates the cached artifacts, rerun is
//! driven by `cargo:rerun-if-changed` directives at the end.

use std::io::Write;
use std::path::{Path, PathBuf};

use uor_ontology::model::IndividualValue;
use uor_ontology::Ontology;

#[allow(clippy::needless_borrow)]
fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let ontology = Ontology::full();

    write_defaults(&ontology, &out_dir);
    write_keywords(&ontology, &out_dir);
    write_shape_requirements(&ontology, &out_dir);

    // Rebuild when any spec namespace changes. The spec crate itself has
    // a fine-grained rebuild-when-changed already, but this build script
    // caches its output, so it needs explicit rerun hooks.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../spec/src");
}

fn write_defaults(ontology: &Ontology, out_dir: &Path) {
    // Find `type:ResidueDefaultModulus` individual and read its
    // `type:defaultValue` integer.
    let modulus = ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .find(|i| i.id == "https://uor.foundation/type/ResidueDefaultModulus")
        .and_then(|i| {
            i.properties.iter().find_map(|(k, v)| {
                if *k == "https://uor.foundation/type/defaultValue" {
                    if let IndividualValue::Int(n) = v {
                        return Some(*n as u64);
                    }
                }
                None
            })
        })
        .unwrap_or(256);

    let body = format!(
        "// @generated by uor-foundation-macros/build.rs — do not edit.\n\
         // Sourced from ontology individual type:ResidueDefaultModulus.\n\
         pub const RESIDUE_DEFAULT_MODULUS: u64 = {modulus};\n"
    );
    let path = out_dir.join("defaults.rs");
    let mut f = std::fs::File::create(&path).expect("write defaults.rs");
    f.write_all(body.as_bytes())
        .expect("write defaults.rs body");
}

fn write_keywords(ontology: &Ontology, out_dir: &Path) {
    // Collect `surfaceForm` values from every `conformance:Shape` individual,
    // strip the `-decl` suffix, and snake-case the result.
    let mut keywords: Vec<String> = ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .filter(|i| i.type_ == "https://uor.foundation/conformance/Shape")
        .filter_map(|i| {
            i.properties.iter().find_map(|(k, v)| {
                if *k == "https://uor.foundation/conformance/surfaceForm" {
                    if let IndividualValue::Str(s) = v {
                        return Some(s.to_string());
                    }
                }
                None
            })
        })
        .map(|form| {
            form.strip_suffix("-decl")
                .unwrap_or(&form)
                .replace('-', "_")
        })
        .collect();
    keywords.sort();
    keywords.dedup();

    let entries = keywords
        .iter()
        .map(|k| format!("    \"{k}\""))
        .collect::<Vec<_>>()
        .join(",\n");
    let body = format!(
        "// @generated by uor-foundation-macros/build.rs — do not edit.\n\
         // Sourced from conformance:Shape individuals' surfaceForm values.\n\
         pub const KNOWN_KEYWORDS: &[&str] = &[\n{entries},\n];\n"
    );
    let path = out_dir.join("keywords.rs");
    let mut f = std::fs::File::create(&path).expect("write keywords.rs");
    f.write_all(body.as_bytes())
        .expect("write keywords.rs body");
}

fn write_shape_requirements(ontology: &Ontology, out_dir: &Path) {
    // For each conformance:Shape individual, collect:
    //   - the keyword (derived from surfaceForm as in write_keywords),
    //   - the required property constraints' surfaceKeyword values in order.
    let mut entries: Vec<(String, Vec<String>)> = Vec::new();
    for shape in ontology
        .namespaces
        .iter()
        .flat_map(|n| n.individuals.iter())
        .filter(|i| i.type_ == "https://uor.foundation/conformance/Shape")
    {
        let form = shape.properties.iter().find_map(|(k, v)| {
            if *k == "https://uor.foundation/conformance/surfaceForm" {
                if let IndividualValue::Str(s) = v {
                    return Some(s.to_string());
                }
            }
            None
        });
        let keyword = match form {
            Some(f) => f.strip_suffix("-decl").unwrap_or(&f).replace('-', "_"),
            None => continue,
        };

        let required: Vec<String> = shape
            .properties
            .iter()
            .filter_map(|(k, v)| {
                if *k != "https://uor.foundation/conformance/requiredProperty" {
                    return None;
                }
                let iri = match v {
                    IndividualValue::IriRef(s) => *s,
                    _ => return None,
                };
                // Resolve the PropertyConstraint individual, read its
                // `surfaceKeyword`.
                ontology
                    .namespaces
                    .iter()
                    .flat_map(|n| n.individuals.iter())
                    .find(|i| i.id == iri)
                    .and_then(|c| {
                        c.properties.iter().find_map(|(ck, cv)| {
                            if *ck == "https://uor.foundation/conformance/surfaceKeyword" {
                                if let IndividualValue::Str(s) = cv {
                                    return Some(s.to_string());
                                }
                            }
                            None
                        })
                    })
            })
            .collect();

        entries.push((keyword, required));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let table_entries = entries
        .iter()
        .map(|(kw, reqs)| {
            let vlist = reqs
                .iter()
                .map(|r| format!("\"{r}\""))
                .collect::<Vec<_>>()
                .join(", ");
            format!("    (\"{kw}\", &[{vlist}])")
        })
        .collect::<Vec<_>>()
        .join(",\n");
    let body = format!(
        "// @generated by uor-foundation-macros/build.rs — do not edit.\n\
         // Each entry: (declaration keyword, &[required body keys]).\n\
         // Sourced from conformance:Shape.requiredProperty -> PropertyConstraint.surfaceKeyword.\n\
         pub const SHAPE_REQUIRED_KEYS: &[(&str, &[&str])] = &[\n{table_entries},\n];\n"
    );
    let path = out_dir.join("shape_requirements.rs");
    let mut f = std::fs::File::create(&path).expect("write shape_requirements.rs");
    f.write_all(body.as_bytes())
        .expect("write shape_requirements.rs body");
}
