// @generated by uor-crate from uor-ontology — do not edit manually

//! `type/` namespace — Runtime type declarations that parameterize the resolution pipeline. Types are declared by Prism applications and resolved to partitions of the ring..
//!
//! Space: User

use crate::enums::MetricAxis;
use crate::enums::WittLevel;
use crate::HostTypes;

/// A runtime type declaration. The root class for all UOR types. Each TypeDefinition, when resolved, produces a partition of the ring at the specified quantum level.
/// Disjoint with: Constraint, MetricAxis.
pub trait TypeDefinition<H: HostTypes> {
    /// Associated type for `Element`.
    type Element: crate::kernel::address::Element<H>;
    /// The content-derived address of this type definition, uniquely identifying the type in the UOR address space.
    fn content_address(&self) -> &Self::Element;
}

/// A primitive type defined by a fixed bit width. The carrier is the entire ring Z/(2^n)Z at the specified quantum level.
pub trait PrimitiveType<H: HostTypes>: TypeDefinition<H> {
    /// The bit width of a primitive type (the quantum level n). The carrier is Z/(2^n)Z.
    fn bit_width(&self) -> u64;
}

/// A product (Cartesian) type formed from multiple component types. The carrier is the product of the component carriers.
pub trait ProductType<H: HostTypes>: TypeDefinition<H> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: TypeDefinition<H>;
    /// A component type in a product type.
    fn component(&self) -> &[Self::TypeDefinition];
}

/// A sum (disjoint union) type formed from multiple variant types. The carrier is the disjoint union of the variant carriers.
pub trait SumType<H: HostTypes>: TypeDefinition<H> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: TypeDefinition<H>;
    /// A variant type in a sum type. Ordering contract: variants are returned in canonical content-fingerprint order (ascending), matching the canonicalization used by coproduct_shape! and the content-address hashing pipeline, so introspection via variant() and the algebra_id derived from the same type agree on which variant is 'left' and which is 'right'. Author-order is not preserved.
    fn variant(&self) -> &[Self::TypeDefinition];
    /// Associated type for `TagSite`.
    type TagSite: crate::bridge::partition::TagSite<H>;
    /// The tag site distinguishing variants of this sum type at runtime (ST_6). Stored at the physical layout position max(SITE_COUNT(A), SITE_COUNT(B)) so the tag cannot collide with any inherited bookkeeping site when either operand is itself a coproduct.
    fn tag_site(&self) -> &Self::TagSite;
}

/// A type formed by constraining a base type with a predicate. The carrier is the subset of the base carrier satisfying the constraint.
pub trait ConstrainedType<H: HostTypes>: TypeDefinition<H> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: TypeDefinition<H>;
    /// The base type that a constrained type restricts.
    fn base_type(&self) -> &Self::TypeDefinition;
    /// Associated type for `Constraint`.
    type Constraint: Constraint<H>;
    /// A typed constraint object applied to this constrained type. Replaces the deprecated string-based type:constraint property.
    fn has_constraint(&self) -> &[Self::Constraint];
    /// Associated type for `HolonomyGroup`.
    type HolonomyGroup: crate::bridge::observable::HolonomyGroup<H>;
    /// The HolonomyGroup of this type. Computed by the MonodromyResolver.
    fn holonomy_group(&self) -> &Self::HolonomyGroup;
    /// Associated type for `MonodromyClass`.
    type MonodromyClass: crate::bridge::observable::MonodromyClass<H>;
    /// The MonodromyClass classifying this type as flat or twisted.
    fn monodromy_class(&self) -> &Self::MonodromyClass;
    /// Whether this ConstrainedType has been classified as FlatType or TwistedType by the MonodromyResolver. The MN_8 identity guarantees this is a bivalent classification: holonomyClassified(T) iff isFlatType(T) xor isTwistedType(T).
    fn holonomy_classified(&self) -> bool;
}

/// A composable predicate that refines a type by pinning one or more site coordinates. Constraints are the parameterization mechanism for ConstrainedType.
/// Disjoint with: TypeDefinition, MetricAxis.
pub trait Constraint<H: HostTypes> {
    /// The metric axis along which this constraint operates: vertical (ring), horizontal (Hamming), or diagonal (incompatibility).
    fn metric_axis(&self) -> MetricAxis;
    /// Associated type for `SiteIndex`.
    type SiteIndex: crate::bridge::partition::SiteIndex<H>;
    /// A site coordinate that this constraint pins when applied.
    fn pins_sites(&self) -> &[Self::SiteIndex];
    /// The cost of applying this constraint in terms of axis crossings: the number of metric boundaries that must be traversed.
    fn crossing_cost(&self) -> u64;
}

/// A TypeDefinition certified to satisfy the UOR completeness criterion (IT_7d): its constraint nerve N(C) has Euler characteristic χ = n and all Betti numbers β_k = 0. A CompleteType guarantees that resolution closes the site budget in O(1) — no iterative refinement is required. Completeness is attested by a cert:CompletenessCertificate linked via cert:certifiedType. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait CompleteType<H: HostTypes>: TypeDefinition<H> {}

/// A ConstrainedType actively undergoing the completeness certification pipeline. Links to the resolver:ResolutionState tracking the current iteration and to the resolver:CechNerve being computed. Disjoint from CompleteType (which is already certified). This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: CompleteType.
pub trait CompletenessCandidate<H: HostTypes>: ConstrainedType<H> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<H>;
    /// The ConstrainedType being evaluated for completeness by this CompletenessCandidate.
    fn completeness_candidate(&self) -> &[Self::ConstrainedType];
    /// Associated type for `CechNerve`.
    type CechNerve: crate::bridge::resolver::CechNerve<H>;
    /// The constraint nerve being computed for this candidate. The CompletenessResolver reads χ(N(C)) from this nerve at each iteration via resolver:nerveEulerCharacteristic.
    fn candidate_nerve(&self) -> &Self::CechNerve;
}

/// A record of a single site-closing event: one constraint application that reduced the FreeRank deficit. Carries the applied constraint and the sitesClosed count. Forms the ordered audit trail between ConstrainedType and CompleteType.
pub trait CompletenessWitness<H: HostTypes> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<H>;
    /// The constraint applied in this witness step.
    fn witness_constraint(&self) -> &Self::Constraint;
    /// Number of sites closed by this witness step.
    fn sites_closed(&self) -> u64;
}

/// A specification of the desired topological properties of a type to be synthesised. Carries a target Euler characteristic (targetEulerCharacteristic) and a target Betti profile (zero or more targetBettiNumber assertions). The minimal goal for O(1) resolution is: targetEulerCharacteristic = n and all targetBettiNumber = 0 — the IT_7d profile.
pub trait TypeSynthesisGoal<H: HostTypes> {
    /// The target χ(N(C)) value. For O(1) resolution: set equal to n (the quantum level).
    fn target_euler_characteristic(&self) -> i64;
    /// Non-functional. Each assertion specifies a target Betti number value for a given homological degree. Multiple assertions permitted, one per degree.
    fn target_betti_number(&self) -> &[u64];
    /// Whether the target signature of this TypeSynthesisGoal is a ForbiddenSignature. If true, synthesis is provably impossible.
    fn target_forbidden(&self) -> bool;
}

/// The output of a TypeSynthesisResolver run. Contains the SynthesizedType, the realised topological signature (as a SynthesisSignature), and the SynthesisTrace recording the construction steps.
pub trait TypeSynthesisResult<H: HostTypes> {}

/// A ConstrainedType produced by the TypeSynthesisResolver. Distinguished from a hand-authored ConstrainedType by the presence of a type:synthesisResult link. May or may not be a CompleteType, depending on the synthesis goal. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait SynthesizedType<H: HostTypes>: ConstrainedType<H> {
    /// Associated type for `TypeSynthesisResult`.
    type TypeSynthesisResult: TypeSynthesisResult<H>;
    /// Links a SynthesizedType back to the synthesis run that produced it.
    fn synthesis_result(&self) -> &Self::TypeSynthesisResult;
}

/// The minimal set of constraints in the SynthesizedType's constraint set that is sufficient to realise the target topological signature. The minimality criterion is that removing any single member changes the realised signature.
pub trait MinimalConstraintBasis<H: HostTypes> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<H>;
    /// Non-functional. One assertion per constraint in the minimal basis.
    fn basis_constraint(&self) -> &[Self::Constraint];
    /// The cardinality of the minimal basis. The theoretical lower bound is n (one constraint per site).
    fn basis_size(&self) -> u64;
}

/// A ConstrainedType T' over R_{n+1} obtained by extending a ConstrainedType T over R_n. Carries a link to the base type (liftBase), the quantum level it lifts to (liftTargetLevel), and the LiftObstruction (if the lift fails to transfer completeness). A WittLift is a CompleteType iff its LiftObstruction is trivial.
pub trait WittLift<H: HostTypes> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<H>;
    /// The base type being lifted to the next quantum level.
    fn lift_base(&self) -> &Self::ConstrainedType;
    /// The quantum level this lift targets.
    fn lift_target_level(&self) -> WittLevel;
    /// Associated type for `LiftObstruction`.
    type LiftObstruction: LiftObstruction<H>;
    /// The LiftObstruction for this lift. Trivial (zero class) iff the lift inherits completeness.
    fn lift_obstruction(&self) -> &Self::LiftObstruction;
}

/// The algebraic obstruction to a WittLift inheriting the completeness of its base type. Computed as the image of the spectral sequence differential d_2. If trivial (zero), the base type's completeness lifts. If non-trivial, at least one additional constraint is needed at the new quantum level.
pub trait LiftObstruction<H: HostTypes> {
    /// True iff the obstruction class is zero — the base type's completeness transfers to the lifted quantum level without additional constraints.
    fn obstruction_trivial(&self) -> bool;
    /// Associated type for `SiteIndex`.
    type SiteIndex: crate::bridge::partition::SiteIndex<H>;
    /// The site at the new quantum level where the obstruction is located. Ranges over the new bit position introduced at Q_{n+1}.
    fn obstruction_site(&self) -> &Self::SiteIndex;
}

/// A ConstrainedType whose HolonomyGroup is non-trivial — at least one closed constraint path produces a non-identity dihedral element. A TwistedType may still be a CompleteType (IT_7d is a homological, not holonomic, criterion), but its resolution paths require tracking dihedral accumulation. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: FlatType.
pub trait TwistedType<H: HostTypes>: ConstrainedType<H> {}

/// A ConstrainedType whose HolonomyGroup is trivial — all closed constraint paths have identity monodromy. The constraint configuration is topologically flat: resolution is path-independent. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: TwistedType.
pub trait FlatType<H: HostTypes>: ConstrainedType<H> {}

/// A type representing a superposition of site states where sites carry complex amplitudes rather than binary pinned/free assignments. Ontological realisation of RC_5 (Amendment 32). This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait SuperposedSiteState<H: HostTypes>: TypeDefinition<H> {
    /// The amplitude coefficient for this superposed site state.
    fn amplitude(&self) -> H::Decimal;
    /// Whether the amplitude vector of this SuperposedSiteState satisfies the normalization condition Σ|αᵢ|² = 1 (QM_5). Set by the SuperpositionResolver after verification.
    fn normalization_verified(&self) -> bool;
}

/// A topological signature (χ, β_k) that is formally impossible to achieve for any ConstrainedType. Witnessed by an ImpossibilityWitness in proof/.
pub trait ForbiddenSignature<H: HostTypes> {}

/// A site state that has undergone projective collapse from a SuperposedSiteState to a definitive classical value. Topologically equivalent to a classically pinned site (QM_2).
pub trait CollapsedSiteState<H: HostTypes> {
    /// Associated type for `SuperposedSiteState`.
    type SuperposedSiteState: SuperposedSiteState<H>;
    /// The SuperposedSiteState from which this CollapsedSiteState was produced by projective measurement.
    fn collapsed_from(&self) -> &Self::SuperposedSiteState;
    /// The amplitude of the surviving branch after projective collapse. |α|² is the probability of this outcome under the Born rule.
    fn surviving_amplitude(&self) -> H::Decimal;
}

/// An ordered composition of WittLift steps from liftSourceLevel (Q_j) to liftTargetLevel (Q_k) for any j < k. The canonical object certifying type completeness at arbitrary Q_k.
pub trait LiftChain<H: HostTypes> {
    /// The quantum level at the base of the chain.
    fn lift_source_level(&self) -> WittLevel;
    /// The number of WittLift steps in the chain (k - j).
    fn chain_length(&self) -> u64;
    /// Associated type for `WittLift`.
    type WittLift: WittLift<H>;
    /// A WittLift step in this chain. Non-functional: one per step.
    fn chain_step(&self) -> &[Self::WittLift];
    /// Associated type for `ObstructionChain`.
    type ObstructionChain: ObstructionChain<H>;
    /// The full obstruction history of this chain.
    fn chain_obstruction_profile(&self) -> &Self::ObstructionChain;
    /// The basis size of the CompleteType at the chain target level.
    fn resolved_basis_size(&self) -> u64;
}

/// The complete ordered sequence of LiftObstruction records encountered and resolved along a LiftChain. An empty ObstructionChain means the tower is flat.
pub trait ObstructionChain<H: HostTypes> {
    /// Associated type for `LiftObstruction`.
    type LiftObstruction: LiftObstruction<H>;
    /// A non-trivial LiftObstruction in this chain. Non-functional.
    fn obstruction_at(&self) -> &[Self::LiftObstruction];
    /// Total number of non-trivial LiftObstruction records.
    fn obstruction_count(&self) -> u64;
    /// True iff obstructionCount = 0 (flat tower).
    fn is_flat(&self) -> bool;
}

/// The space of all CompleteTypes over R_n at a given quantum level.
pub trait ModuliSpace<H: HostTypes> {
    /// The quantum level at which this moduli space is defined.
    fn moduli_witt_level(&self) -> WittLevel;
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<H>;
    /// A CompleteType that is a point of this moduli space.
    fn moduli_point(&self) -> &[Self::CompleteType];
    /// The dimension of this moduli space.
    fn moduli_dimension(&self) -> u64;
}

/// A stratum indexed by a conjugacy class of subgroups of D_{2^n}.
pub trait HolonomyStratum<H: HostTypes> {
    /// Associated type for `MonodromyClass`.
    type MonodromyClass: crate::bridge::observable::MonodromyClass<H>;
    /// The MonodromyClass indexing this stratum.
    fn stratum_holonomy_class(&self) -> &Self::MonodromyClass;
    /// The codimension of this stratum within the moduli space.
    fn stratum_codimension(&self) -> u64;
    /// Associated type for `ModuliSpace`.
    type ModuliSpace: ModuliSpace<H>;
    /// The moduli space containing this stratum.
    fn stratum_moduli(&self) -> &Self::ModuliSpace;
}

/// A one-parameter family of constraint configurations parameterizing a path.
pub trait DeformationFamily<H: HostTypes> {
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<H>;
    /// A CompleteType along the deformation path.
    fn family_parameter(&self) -> &[Self::CompleteType];
    /// Whether every member of this deformation family remains a CompleteType.
    fn family_preserves_completeness(&self) -> bool;
}

/// The versal deformation of a CompleteType T.
pub trait VersalDeformation<H: HostTypes> {
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<H>;
    /// The CompleteType at the base of this versal deformation.
    fn versal_base(&self) -> &Self::CompleteType;
    /// The dimension of the versal deformation space.
    fn versal_dimension(&self) -> u64;
}

/// The map induced by WittLift from one moduli space to the next.
pub trait ModuliTowerMap<H: HostTypes> {
    /// Associated type for `ModuliSpace`.
    type ModuliSpace: ModuliSpace<H>;
    /// The source moduli space of this tower map.
    fn tower_map_source(&self) -> &Self::ModuliSpace;
}

/// The adjunction between the type lattice and the site lattice. The upper adjoint is type closure; the lower adjoint is site interior. σ = lower adjoint evaluation; r = complement of upper adjoint image.
pub trait GaloisConnection<H: HostTypes> {
    /// Associated type for `TermExpression`.
    type TermExpression: crate::kernel::schema::TermExpression<H>;
    /// The upper adjoint (type closure) of the Galois connection, expressed as a symbolic formula string.
    fn upper_adjoint(&self) -> &Self::TermExpression;
    /// The lower adjoint (site interior) of the Galois connection, expressed as a symbolic formula string.
    fn lower_adjoint(&self) -> &Self::TermExpression;
    /// The fixpoint condition for the Galois connection: when upper(lower(T)) = T, the type is complete.
    fn fixpoint_condition(&self) -> &Self::TermExpression;
    /// Description of the refinement direction: ascending in type lattice corresponds to descending in site freedom.
    fn refinement_direction(&self) -> u64;
    /// The closure property of a Galois connection.
    fn galois_closure_property(&self) -> &Self::TermExpression;
    /// The interior property of a Galois connection.
    fn galois_interior_property(&self) -> &Self::TermExpression;
}

/// A morphism T₁ → T₂ witnessing that T₁ is a subtype of T₂: the constraint set of T₁ is a superset of the constraint set of T₂.
pub trait TypeInclusion<H: HostTypes>: crate::user::morphism::Transform<H> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<H>;
    /// The subtype (more constraints).
    fn inclusion_source(&self) -> &Self::ConstrainedType;
    /// The supertype (fewer constraints).
    fn inclusion_target(&self) -> &Self::ConstrainedType;
    /// True iff constraints(source) ⊇ constraints(target). Computed, not asserted.
    fn inclusion_witness(&self) -> bool;
}

/// The partial order on types induced by TypeInclusion. The top element is PrimitiveType (no constraints); the bottom elements are CompleteTypes (all sites pinned).
pub trait SubtypingLattice<H: HostTypes> {
    /// Maximum chain length from PrimitiveType (top) to any CompleteType (bottom). Equals the site budget n at quantum level Q_k.
    fn lattice_depth(&self) -> u64;
}

/// Declarative defaults for type:Constraint subclasses, consumed by #\[derive(ConstrainedType)\] at macro-crate build time.
pub trait ConstraintDefaults<H: HostTypes> {
    /// Default integer value for the named constraint default.
    fn default_value(&self) -> i64;
}

/// Parametric constraint carrier consumed by the codegen to emit `BoundConstraint\<O: Observable, B: BoundShape\>` in the Rust foundation. The (observable, bound_shape) pair picks the predicate form; the typed datatype properties (modulus, residue, hammingBound, ...) carry the parameters for that specific kind. Replaces the seven v0.2.1 enumerated Constraint subclasses with a parametric form; the legacy names survive as Rust type aliases (ResidueConstraint, HammingConstraint, ...).
pub trait BoundConstraint<H: HostTypes>: Constraint<H> {
    /// The modulus m of a residue constraint: x ≡ r (mod m).
    fn modulus(&self) -> u64;
    /// The residue value r of a residue constraint: x ≡ r (mod m).
    fn residue(&self) -> u64;
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<H>;
    /// The carry propagation pattern of a carry constraint, expressed as a Datum at the appropriate quantum level.
    fn carry_pattern(&self) -> &Self::Datum;
    /// The minimum factorization depth required by a depth constraint.
    fn min_depth(&self) -> u64;
    /// The maximum factorization depth allowed by a depth constraint.
    fn max_depth(&self) -> u64;
    /// Upper bound on the Hamming weight of the Datum.
    fn hamming_bound(&self) -> u64;
    /// Zero-based index of the pinned site coordinate.
    fn site_index(&self) -> u64;
    /// The value the pinned site coordinate must equal (a Datum in the set {0, 1}).
    fn site_value(&self) -> &Self::Datum;
    /// Constant offset defining the affine subspace.
    fn affine_offset(&self) -> &Self::Datum;
    /// A generator of the affine subspace. Non-functional: multiple generators span the subspace.
    fn affine_generator(&self) -> &[Self::Datum];
    /// Associated type for `Observable`.
    type Observable: crate::bridge::observable::Observable<H>;
    /// The observable:Observable whose values this BoundConstraint bounds. Picks which datum projection is being constrained.
    fn bound_observable(&self) -> &Self::Observable;
    /// Associated type for `BoundShape`.
    type BoundShape: BoundShape<H>;
    /// The predicate form this BoundConstraint imposes on its bound observable. Closed enumeration with exactly six named individuals (EqualBound, LessEqBound, GreaterEqBound, RangeContainBound, ResidueClassBound, AffineEqualBound).
    fn bound_shape(&self) -> &Self::BoundShape;
    /// The BoundConstraint's parameters in canonical string form (e.g., 'modulus=256;residue=255' for a residue class bound). Non-functional — the string-form encoding is the canonical serialization; typed accessors on the Rust side unpack it via the per-type-alias constructors.
    fn bound_arguments(&self) -> &H::HostString;
}

/// The predicate form a BoundConstraint imposes on its bound observable. Closed enumeration with exactly six named individuals (EqualBound, LessEqBound, GreaterEqBound, RangeContainBound, ResidueClassBound, AffineEqualBound). Adding a new bound shape is an ontology+grammar+codegen edit on the same protocol as adding a Witt level.
pub trait BoundShape<H: HostTypes> {}

/// A conjunction of BoundConstraint instances. The conjuncts property is ordered. Replaces the v0.2.1 CompositeConstraint enumeration; the legacy name survives as a Rust type alias (CompositeConstraint\<const N: usize\> = Conjunction\<N\>).
pub trait Conjunction<H: HostTypes>: Constraint<H> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<H>;
    /// A component constraint of this composite constraint.
    fn composed_from(&self) -> &[Self::Constraint];
    /// Associated type for `BoundConstraint`.
    type BoundConstraint: BoundConstraint<H>;
    /// An ordered list of BoundConstraint individuals that this Conjunction composes. Non-functional — multiple conjuncts span the conjunction.
    fn conjuncts(&self) -> &[Self::BoundConstraint];
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `TypeDefinition<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullTypeDefinition<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullTypeDefinition<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullTypeDefinition<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullTypeDefinition<H> = NullTypeDefinition {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullTypeDefinition<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `PrimitiveType<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullPrimitiveType<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullPrimitiveType<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullPrimitiveType<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullPrimitiveType<H> = NullPrimitiveType {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullPrimitiveType<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}
impl<H: HostTypes> PrimitiveType<H> for NullPrimitiveType<H> {
    fn bit_width(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `ProductType<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullProductType<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullProductType<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullProductType<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullProductType<H> = NullProductType {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullProductType<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}
impl<H: HostTypes> ProductType<H> for NullProductType<H> {
    type TypeDefinition = NullTypeDefinition<H>;
    fn component(&self) -> &[Self::TypeDefinition] {
        &[]
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `SumType<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullSumType<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullSumType<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullSumType<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullSumType<H> = NullSumType {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullSumType<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}
impl<H: HostTypes> SumType<H> for NullSumType<H> {
    type TypeDefinition = NullTypeDefinition<H>;
    fn variant(&self) -> &[Self::TypeDefinition] {
        &[]
    }
    type TagSite = crate::bridge::partition::NullTagSite<H>;
    fn tag_site(&self) -> &Self::TagSite {
        &<crate::bridge::partition::NullTagSite<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `CompleteType<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullCompleteType<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullCompleteType<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullCompleteType<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullCompleteType<H> = NullCompleteType {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullCompleteType<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}
impl<H: HostTypes> CompleteType<H> for NullCompleteType<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `TypeSynthesisGoal<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullTypeSynthesisGoal<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullTypeSynthesisGoal<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullTypeSynthesisGoal<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullTypeSynthesisGoal<H> = NullTypeSynthesisGoal {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeSynthesisGoal<H> for NullTypeSynthesisGoal<H> {
    fn target_euler_characteristic(&self) -> i64 {
        0
    }
    fn target_betti_number(&self) -> &[u64] {
        &[]
    }
    fn target_forbidden(&self) -> bool {
        false
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `TypeSynthesisResult<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullTypeSynthesisResult<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullTypeSynthesisResult<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullTypeSynthesisResult<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullTypeSynthesisResult<H> = NullTypeSynthesisResult {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeSynthesisResult<H> for NullTypeSynthesisResult<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `LiftObstruction<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullLiftObstruction<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullLiftObstruction<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullLiftObstruction<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullLiftObstruction<H> = NullLiftObstruction {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> LiftObstruction<H> for NullLiftObstruction<H> {
    fn obstruction_trivial(&self) -> bool {
        false
    }
    type SiteIndex = crate::bridge::partition::NullSiteIndex<H>;
    fn obstruction_site(&self) -> &Self::SiteIndex {
        &<crate::bridge::partition::NullSiteIndex<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `SuperposedSiteState<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullSuperposedSiteState<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullSuperposedSiteState<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullSuperposedSiteState<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullSuperposedSiteState<H> = NullSuperposedSiteState {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> TypeDefinition<H> for NullSuperposedSiteState<H> {
    type Element = crate::kernel::address::NullElement<H>;
    fn content_address(&self) -> &Self::Element {
        &<crate::kernel::address::NullElement<H>>::ABSENT
    }
}
impl<H: HostTypes> SuperposedSiteState<H> for NullSuperposedSiteState<H> {
    fn amplitude(&self) -> H::Decimal {
        H::EMPTY_DECIMAL
    }
    fn normalization_verified(&self) -> bool {
        false
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `ForbiddenSignature<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullForbiddenSignature<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullForbiddenSignature<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullForbiddenSignature<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullForbiddenSignature<H> = NullForbiddenSignature {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> ForbiddenSignature<H> for NullForbiddenSignature<H> {}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `CollapsedSiteState<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullCollapsedSiteState<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullCollapsedSiteState<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullCollapsedSiteState<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullCollapsedSiteState<H> = NullCollapsedSiteState {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> CollapsedSiteState<H> for NullCollapsedSiteState<H> {
    type SuperposedSiteState = NullSuperposedSiteState<H>;
    fn collapsed_from(&self) -> &Self::SuperposedSiteState {
        &<NullSuperposedSiteState<H>>::ABSENT
    }
    fn surviving_amplitude(&self) -> H::Decimal {
        H::EMPTY_DECIMAL
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `ObstructionChain<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullObstructionChain<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullObstructionChain<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullObstructionChain<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullObstructionChain<H> = NullObstructionChain {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> ObstructionChain<H> for NullObstructionChain<H> {
    type LiftObstruction = NullLiftObstruction<H>;
    fn obstruction_at(&self) -> &[Self::LiftObstruction] {
        &[]
    }
    fn obstruction_count(&self) -> u64 {
        0
    }
    fn is_flat(&self) -> bool {
        false
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `DeformationFamily<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullDeformationFamily<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullDeformationFamily<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullDeformationFamily<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullDeformationFamily<H> = NullDeformationFamily {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> DeformationFamily<H> for NullDeformationFamily<H> {
    type CompleteType = NullCompleteType<H>;
    fn family_parameter(&self) -> &[Self::CompleteType] {
        &[]
    }
    fn family_preserves_completeness(&self) -> bool {
        false
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `VersalDeformation<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullVersalDeformation<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullVersalDeformation<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullVersalDeformation<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullVersalDeformation<H> = NullVersalDeformation {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> VersalDeformation<H> for NullVersalDeformation<H> {
    type CompleteType = NullCompleteType<H>;
    fn versal_base(&self) -> &Self::CompleteType {
        &<NullCompleteType<H>>::ABSENT
    }
    fn versal_dimension(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `GaloisConnection<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullGaloisConnection<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullGaloisConnection<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullGaloisConnection<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullGaloisConnection<H> = NullGaloisConnection {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> GaloisConnection<H> for NullGaloisConnection<H> {
    type TermExpression = crate::kernel::schema::NullTermExpression<H>;
    fn upper_adjoint(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
    fn lower_adjoint(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
    fn fixpoint_condition(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
    fn refinement_direction(&self) -> u64 {
        0
    }
    fn galois_closure_property(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
    fn galois_interior_property(&self) -> &Self::TermExpression {
        &<crate::kernel::schema::NullTermExpression<H>>::ABSENT
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `SubtypingLattice<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullSubtypingLattice<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullSubtypingLattice<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullSubtypingLattice<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullSubtypingLattice<H> = NullSubtypingLattice {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> SubtypingLattice<H> for NullSubtypingLattice<H> {
    fn lattice_depth(&self) -> u64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `ConstraintDefaults<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullConstraintDefaults<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullConstraintDefaults<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullConstraintDefaults<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullConstraintDefaults<H> = NullConstraintDefaults {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> ConstraintDefaults<H> for NullConstraintDefaults<H> {
    fn default_value(&self) -> i64 {
        0
    }
}

/// Phase 2 (orphan-closure) — resolver-absent default impl of `BoundShape<H>`.
/// Every accessor returns `H::EMPTY_*` sentinels (for scalar / host-typed
/// returns) or a `'static`-lifetime reference to a sibling `Null*`'s `ABSENT`
/// const (for trait-typed returns).  Downstream provides concrete impls;
/// this stub closes the ontology-derived trait orphan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NullBoundShape<H: HostTypes> {
    _phantom: core::marker::PhantomData<H>,
}
impl<H: HostTypes> Default for NullBoundShape<H> {
    fn default() -> Self {
        Self {
            _phantom: core::marker::PhantomData,
        }
    }
}
impl<H: HostTypes> NullBoundShape<H> {
    /// Absent-value sentinel. `&Self::ABSENT` gives every trait-typed accessor a `'static`-lifetime reference target.
    pub const ABSENT: NullBoundShape<H> = NullBoundShape {
        _phantom: core::marker::PhantomData,
    };
}
impl<H: HostTypes> BoundShape<H> for NullBoundShape<H> {}

/// A single value from an ordered domain. siteCount = n (quantization bits).
pub mod scalar_type {
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "quantize(value, range, bits) produces ring element where d_R reflects value proximity";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "n (quantization bits)";
}

/// A value from a finite unordered set. siteCount = ceil(log2(|alphabet|)).
pub mod symbol_type {
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "argmin_{encoding} sum d_delta over observed pairs (CY_5)";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "ceil(log2(|alphabet|))";
}

/// An ordered list of elements with backbone constraint. The free monoid on the element type.
pub mod sequence_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "backbone ordering: elements indexed by position";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "free monoid on element type, backbone constraint";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "sum of element site counts";
}

/// A fixed collection of named fields.
pub mod tuple_type {
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "site ordering follows CY_6 (optimal site ordering)";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "sum of field site counts";
}

/// Nodes with edge constraints. Constraint nerve = graph topology.
pub mod graph_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "edge constraints: adjacency preserved under grounding";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "constraint nerve = graph nerve, beta_k equality";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "sum of node site counts + edge overhead";
}

/// Unordered collection. d_delta is permutation-invariant.
pub mod set_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "permutation invariance: encoding is order-independent";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "d_delta invariant under element permutation, D_{2n} symmetry";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "sum of element site counts";
}

/// Hierarchical structure. beta_1=0 (acyclic), beta_0=1 (connected).
pub mod tree_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "beta_1=0 (acyclic), beta_0=1 (connected)";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "parent-child encoding with acyclicity constraint";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "sum of node site counts";
}

/// Collection of tuples sharing a schema = Sequence(Tuple(S)). Functorial decomposition.
pub mod table_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "shared schema: all rows conform to tuple type S";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "Sequence(Tuple(S)), functorial decomposition";
    /// `structuralSiteCount`
    pub const STRUCTURAL_SITE_COUNT: &str = "row_count * tuple_site_count";
}

/// The structural position preserves TypeInclusion: if T₁ ≤ T₂, then F(T₁) ≤ F(T₂).
pub mod covariant {
    /// `enumVariant` -> `Covariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Covariant";
}

/// The structural position reverses TypeInclusion: if T₁ ≤ T₂, then F(T₂) ≤ F(T₁).
pub mod contravariant {
    /// `enumVariant` -> `Contravariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Contravariant";
}

/// The structural position requires exact type equality: F(T₁) ≤ F(T₂) only if T₁ = T₂.
pub mod invariant {
    /// `enumVariant` -> `Invariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Invariant";
}

/// The structural position ignores the type parameter: F(T₁) ≤ F(T₂) for all T₁, T₂.
pub mod bivariant {
    /// `enumVariant` -> `Bivariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Bivariant";
}

/// The canonical binary disjoint union type whose carrier is L + R.
pub mod either_type {}

/// The canonical A + Unit idiom for optional values.
pub mod option_type {}

/// Default modulus for ResidueConstraint when the #\[uor(residue = X)\] attribute omits the explicit modulus. 256 matches the v0.2.1 reference ring Z/(2^8)Z.
pub mod residue_default_modulus {
    /// `defaultValue`
    pub const DEFAULT_VALUE: i64 = 256;
}

/// Predicate form: `observable(datum) == target`. Used by BoundConstraint instances asserting strict equality of a datum's observable projection to a target value.
pub mod equal_bound {}

/// Predicate form: `observable(datum) <= bound`. Used by hamming, depth, carry, and site-rank bound constraints.
pub mod less_eq_bound {}

/// Predicate form: `observable(datum) >= bound`.
pub mod greater_eq_bound {}

/// Predicate form: `lo <= observable(datum) <= hi`. The datum's observable projection must lie within the inclusive range `\[lo, hi\]`.
pub mod range_contain_bound {}

/// Predicate form: `observable(datum) ≡ residue (mod modulus)`. Used by BoundConstraint instances asserting residue-class membership.
pub mod residue_class_bound {}

/// Predicate form: `observable(datum) == offset + Σ αᵢ·generatorᵢ`. The datum's observable projection must equal an affine combination of the BoundConstraint's affine generators.
pub mod affine_equal_bound {}

/// Parametric replacement for the v0.2.1 ResidueConstraint class: (observable:ValueModObservable, type:ResidueClassBound). The Rust foundation exposes this kind via the `ResidueConstraint` type alias with `pub const fn new(modulus, residue)`.
pub mod residue_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "modulus=256;residue=0";
    /// `boundObservable` -> `ValueModObservable`
    pub const BOUND_OBSERVABLE: &str = "https://uor.foundation/observable/ValueModObservable";
    /// `boundShape` -> `ResidueClassBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/ResidueClassBound";
}

/// Parametric replacement for the v0.2.1 HammingConstraint class: (observable:HammingMetric, type:LessEqBound). The Rust foundation exposes this kind via the `HammingConstraint` type alias with `pub const fn new(bound)`.
pub mod hamming_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "bound=0";
    /// `boundObservable` -> `HammingMetric`
    pub const BOUND_OBSERVABLE: &str = "https://uor.foundation/observable/HammingMetric";
    /// `boundShape` -> `LessEqBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/LessEqBound";
}

/// Parametric replacement for the v0.2.1 DepthConstraint class: (derivation:DerivationDepthObservable, type:LessEqBound).
pub mod depth_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "min_depth=0;max_depth=0";
    /// `boundObservable` -> `DerivationDepthObservable`
    pub const BOUND_OBSERVABLE: &str =
        "https://uor.foundation/derivation/DerivationDepthObservable";
    /// `boundShape` -> `LessEqBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/LessEqBound";
}

/// Parametric replacement for the v0.2.1 CarryConstraint class: (carry:CarryDepthObservable, type:LessEqBound).
pub mod carry_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "bound=0";
    /// `boundObservable` -> `CarryDepthObservable`
    pub const BOUND_OBSERVABLE: &str = "https://uor.foundation/carry/CarryDepthObservable";
    /// `boundShape` -> `LessEqBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/LessEqBound";
}

/// Parametric replacement for the v0.2.1 SiteConstraint class: (partition:FreeRankObservable, type:LessEqBound).
pub mod site_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "site_index=0";
    /// `boundObservable` -> `FreeRankObservable`
    pub const BOUND_OBSERVABLE: &str = "https://uor.foundation/partition/FreeRankObservable";
    /// `boundShape` -> `LessEqBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/LessEqBound";
}

/// Parametric replacement for the v0.2.1 AffineConstraint class: (observable:ValueModObservable, type:AffineEqualBound).
pub mod affine_constraint_kind {
    /// `boundArguments`
    pub const BOUND_ARGUMENTS: &str = "offset=0";
    /// `boundObservable` -> `ValueModObservable`
    pub const BOUND_OBSERVABLE: &str = "https://uor.foundation/observable/ValueModObservable";
    /// `boundShape` -> `AffineEqualBound`
    pub const BOUND_SHAPE: &str = "https://uor.foundation/type/AffineEqualBound";
}
